### ISSUE TITLE
Remove "doWeneedThis" field from GetPeers definition inside ripple.proto

### ISSUE THREAD

**Issue by kravets** [ripple/rippled#144]
The comment says the only reason the field exists is due to an assert somewhere else in the code.
IMHO, in principle empty messages should be legal became they represent an efficient way to communicate an event when no payload is necessary. This issue remains open for tracking purposes until it's handled by new peer finder code replacement code mentioned by David.

**Comment by dokterbob** [comment]
RLY?

**Comment by dokterbob** [comment]
Sorry, these bugs had been outstanding for so long that I stopped taking Ripple seriously. (Until then I was about to launch a gateway). So my remark is a mere expression of embafflement.

**Comment by nbougalis** [comment]
You are right to be baffled and I completely understand how you feel, and don’t blame you a bit. Honestly, it’s a bit embarrassing that these lingered as long as they did.

We had switched to tracking issued on a (originally public but eventually private) JIRA board by the time these were made and we simply didn’t look at GitHub issues with any regularity, and when we did, it was only the newer ones.

I’m working to transfer our issue tracking back to GitHub, hence the great cleanup of issues.

If it’s any consolation, the `mtGET_PEERS` has long-since been deprecated and is going to be removed in the near feature, taking `doWeNeedThis` with it.

Also, while not strictly needed by the underlying protocol buffers engine, our higher-levels implementation did need it, since it required all messages to be of non-zero size.
