### ISSUE TITLE
ld: library not found for -lboost_context

### ISSUE THREAD

**Issue by ajbraus** [ripple/rippled#1698]
When I run the [OSX Build Instructions](https://wiki.ripple.com/OSX_Build_Instructions) I get this error when I run scons.

```
ld: library not found for -lboost_context
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [build/clang.release/rippled] Error 1
scons: building terminated because of errors.
```

My `.bashrc` has the BOOST_ROOT path set.

```
export BOOST_ROOT=/Users/<<USERNAME>>/dev/boost_1_56_0
```

**Comment by nbougalis** [comment]
Thank you for reporting this. You are likely stumbling because of the confusing language on with the wiki page, which I will update. The `boost_1_56_0` bit would be applicable only if you were compiling Boost 1.56.0 (the latest at the time the page was updated). But if you were using, for example, Boost 1.60.0, then it would be `boost_1_60_0`. Etc.

Can you check which version of Boost you download and compiled?

**Comment by ajbraus** [comment]
That fixed it!
