### ISSUE TITLE
Transaction success, but amount not being deducted from account balance.

### ISSUE THREAD

**Issue by shambhavi1993** [ripple/rippled#1720]
using POSTER for firefox to run JSON_RPC request, I successfully did a transaction, signed it and verified it.

All of the above mentioned steps worked successfully, but when using account_info method I check the amount of the sender's address I see that the amount is the same as before transaction processing.

Please let me know what I'm doing wrong and what would be the possible solution.

**Comment by nbougalis** [comment]
This is very vague. Was this done on the live network or a standalone server you are using to test? Can you provide the transaction ID that was returned? Can you provide the source and target accounts?

Note: accounts begin with an `r` (for example `ra7eH7cxxhNnMzBW6FVoWcrfHNYPLX58vr`). Be careful to **_NOT_** post any account secret keys (they begin with an `s`).

**Comment by shambhavi1993** [comment]
I'm running stand alone server on local environment for development purpose.

Transaction ID:  1200002280000000240000ACA4201B0145EAB961D5038D7EA4C680000000000000000000000000005553440000000000B5F762798A53D543A014CAF8B297CFF8F2F937E868400000000000000A7321026497DC1221D3D29B29529AD3E1C056F1465FF11870196BC05E83B5B715FAF23E744630440220375165032E3AFF4EFF5CEF5D495293A4DDEB5603B041720D0666AD1E6E9C9FD602201F3D7CC6F5E52F424C96088CB1534ABE9512D0756C05A016B22BB73DDD8A478A8114B5F762798A53D543A014CAF8B297CFF8F2F937E883148AA33ED00FB66B7242456238FE72204E2C0F03C6
Source account: rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh
Target account:  rDesoxdoQsoaiE7SZkHbLmKvX5Umkny8U3

**Comment by nbougalis** [comment]
A `tesSUCCESS` code is not finalized until the transaction appears in a validated ledger. If you're running in standalone mode (that is, if you've used the `-a` command line argument) then this won't happen automatically.

The server isn't running the consensus process when it's in standalone mode. You need to use the `ledger_accept` command manually.

If you need to test, you are better off configuring your server to run in regular mode, instead of standalone, and simply not connect to the main network. To do that, simply remove the `[ips]` and `[ips_fixed]` entries from your server config, and set:

    [peer_private]
    1

Then setup the server as a validator, following the instructions here: https://ripple.com/build/rippled-setup/#validator-setup
