### ISSUE TITLE
path_find not returning paths to XRP

### ISSUE THREAD

**Issue by cometburn** [ripple/rippled#2146]
```
{
	"id": "XRP",
	"command": "path_find",
	"subcommand": "create",
	"source_account": "XXXX",
	"send_max": {
		"currency": "ETH",
		"value": "1",
		"issuer": "ZZZZ"
	},
	"destination_account": "XXXX",
	"destination_amount": "-1"
}
```
provided that:
- XXXX has ETH balance
- XXXX has trustline to ZZZZ

when i send that command through websocket, it doesn't return any paths. 

Can anyone enlighten me on this?

**Comment by JoelKatz** [comment]
It's hard to know exactly what the issue is without seeing the exact situation. Two possibilities:
1) You are looking at the immediate reply to the path creation rather than waiting for the pathfinding to complete and provide a full reply. The immediate reply only finds "obvious" paths.
2) There is no path that will work. For example, there may be no liquidity at all between ETH/ZZZZ and XRP.

**Comment by cometburn** [comment]
Hello Sir, Thank you for replying. 

What I'm doing is finding paths for ETH to XRP...

![screen shot 2017-06-17 at 09 54 44](https://user-images.githubusercontent.com/12859640/27249250-5322a42a-5343-11e7-935d-77c4dc89d8ba.png)

but "alternatives" is empty..

**Comment by cometburn** [comment]
also on the documentation, it says

> You can specify "-1" (for XRP) or provide -1 as the contents of the value field (for non-XRP currencies).

**Comment by JoelKatz** [comment]
The source account does not hold any of the asset it's trying to send, nor can it borrow any.
