### ISSUE TITLE
Submit fails with: Unable to parse request

### ISSUE THREAD

**Issue by got3nks** [ripple/rippled#2244]
```
root@xx:~# curl -H "Content-Type:Application/json" -X POST -d '{"method":"submit","params":[{"offline":false,"secret”:”….”,”tx_json":{"TransactionType":"Payment","Account":"r....","Amount":19279810000,"Destination":"rCoinaUER....","Flags":2147483648,"DestinationTag":1111111111},"fee_mult_max":10000}]}' http://localhost:5005/
root@xx:~# Unable to parse request
```

What is the reason for this failure?

**Comment by mellery451** [comment]
Please read:  https://ripple.com/build/rippled-apis/#specifying-currency-amounts  (TL, DR: amounts generally need to be strings because of js numeric limits)

Also, it looks to me like you have some non-ascii quote characters around your `secret` field - perhaps some editor injected undesirable characters.

**Comment by got3nks** [comment]
Thank you, fixed.
