### ISSUE TITLE
Port to Boost.Beast 1.66.0

### ISSUE THREAD

**Issue by vinniefalco** [ripple/rippled#2323]
Now that Boost.Beast is available in Boost version 1.66.0, it is important to port rippled to this version of Beast in order to take advantage of bug fixes and security fixes.

**Comment by MarkusTeufelberger** [comment]
Which distributions even  ship Boost 1.66.0? As far as I understand it though, beast (in the sense of "the new beast (http-beast)") is vendored in this repository in https://github.com/ripple/rippled/tree/develop/src/beast instead of using the version included in Boost.

Congratulations on getting it into boost by the way! :-)
