### ISSUE TITLE
[enhancement] Change to transfer fees.

### ISSUE THREAD

**Issue by tuloski** [ripple/rippled#2330]
I propose two modifications to the transfer fee logic:

- The possibility for the same issuer to have different transfer fees for different IOUs. This avoids having multiple accounts for a gateway that wants to issue different IOUs with different fees (see gatehub fifth).

- The possibility of "redeeming" the fees from another account. What I mean is that now the fee simply destroys IOUs (they are redeemed by the issuer). Which works until you don't want to have a fixed amount of IOUs or a gateway uses the hot-cold wallet, where the cold wallet issued a fixed amount of IOUs, then disabled master key and set a regular key to a blackhole to prove that no more IOUs will be created. With this feature the issuer can specify another account, where the fees are "collected" in terms of IOUs.

**Comment by MarkusTeufelberger** [comment]
The second request would it also make easier/more expicit for users to see how many (non-XRP) fees they paid in their transactions since there would be an explicit trust line balance change visible in the metadata of the line of the "fee collector" account while also making it easier for the gateway operator to assert that they still have all funds available (e.g. they issue 1000 EUR and have a separate bank account for that - now their issuing account [or ideal: the object on the ledger that represents their issuance, see the first suggestion...] will always show 1000 EUR being issued instead of slowly counting down as fees are being paid.

**Comment by nbougalis** [comment]
Interesting suggestions. I find both to be interesting, but they'd need significant work that may necessitate changes to user-facing APIs, which is never a good idea.

I hope others will chime in and let us know how useful these features would be, how likely they'd be to use them as well as ideas on how to minimize the impact to users.

**Comment by tuloski** [comment]
I think the impact of the "redeeming" can be "minimal" to the users. It could be an optional parameter of the account (to be set with AccountSet as TransferRate) with the target address, that if not used, the fees are exactly as it is now, so users don't have to change anything. If the parameter is used it triggers the new logic.

**Comment by mDuo13** [comment]
I agree, the "fee collector" option seems like it would be fairly straightforward for users. Add a "PayTransferFeesTo" address that one can set with AccountSet, then change the Payment and OfferCreate transactors so that the transfer fees are credited to this account instead of simply subtracted. That said, there are some challenges we'd have to work out before implementing such a thing.

- It seems like the "fee collector" address would have to have a trustline to the issuer and you'd have to respect the limit on the trust line. Otherwise, you could abuse this feature to issue funds to someone who hasn't agreed to hold them, violating a key principle of the XRP Ledger.
    - What happens if the balance on the fee collector's trust line is at or over the limit? Do payments fail, with tecPATH_DRY or another code? Does the transfer fee get waived? Do you revert back to the default behavior of debiting the transfer fee and not crediting it?
- How do you set this up? As long as the "PayTransferFeesTo" field is part of the account like the "TransferRate" is, the ledger have no way of knowing which currencies you might issue in the future and thus no way of knowing which trust lines you'd need.
- Maybe PayTransferFeesTo is a ledger object instead, with a specific currency also specified. Having to look up such objects might make it significantly less efficient to process payments though. (You couldn't have this in the AccountRoot unless it was limited to either one currency or all currencies, because AccountRoot has to be a fixed size.)
    - As long as we're adding extra ledger objects for transfer fee-related settings on specific currencies, we may as well let you define a custom transfer fee for said currency in the same object, probably.
- Maybe you could have a special transaction the fee collector can send, which means, "I'm willing to hold unlimited fees in any currency from <issuing address>"—effectively giving carte blanche to create trust lines as needed and increase their balance over the limits, similar to how Offers can create trust lines, except far more open-ended. This is a little awkward because you'd need to set up the PayTransferFeesTo field and this setting (wherever this setting is stored) as two different transactions, and you have to be able to recognize the in-between states when one side has approved it but the other hasn't.
    - An even weirder way to deal with this would be to have a special signature the fee collector address could attach to the AccountSet transaction to turn on such fee collection. Sort of like a multi-signed transaction or a PaymentChannelClaim. The point being, you have a single atomic transaction that proves both accounts are on board with this arrangement.

**Comment by tuloski** [comment]
@mDuo13 yeah I was thinking the same problems. To me the easiest solution seems that the fee collector has to extend a trust line to the issuer. When the line is at the limit, the fees revert back to the old way, bu maybe it is not the best solution.
But I like the multi-signed way, even though it's much more complex for a "simple" feature.
Also what would happen when the fee collector makes a transaction using those IOUs? Fee-inception :) or he simply doesn't pay any fee...

**Comment by MarkusTeufelberger** [comment]
The "Fee Collector" could be a Check object that is slowly being filled and that can be cashed by the designated collecting account from time to time for example.

> As long as we're adding extra ledger objects for transfer fee-related settings on specific currencies, we may as well let you define a custom transfer fee for said currency in the same object, probably.

YES PLEASE!
