### ISSUE TITLE
Listing website under Buy Ripple category on ripple.com

### ISSUE THREAD

**Issue by ALFAcashier** [ripple/rippled#2366]
Hi!

I've tried contacting you guys via e-mail you've provide on ripple.com to list our service https://www.alfacashier.com/ here https://ripple.com/xrp/buy-xrp/ but nobody is replying for months and I'm only getting some bot reply.

We've been accepting Ripple for more than a year and also been working for 5+ years on cryptocurrency exchange market.

Here is our logo available here - https://www.alfacashier.com/files/e/logo.svg
Maybe you could pass this information to the people who are maintaining ripple.com ? 

Thanks!

**Comment by ALFAcashier** [comment]
Ping @JoelKatz @BobWay @geertweening @emschwartz @intelliot @justmoon @miguelportilla @nbougalis @vhpoet @bachase @seelabs @wilsonianb 

I'm sorry for the spam, but really would like to sort this, thanks!

**Comment by nbougalis** [comment]
Thanks for reaching out; this isn’t the correct channel, but we have forwarded your message to the right group within the company.

Please send me an email to nikb@ripple.com from the address where you can be reached so that I can forward it, in case they have questions for you.

We will now be closing this issue.
