### ISSUE TITLE
Add a [shard_db] setting to the example config for 0.90.0

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2378]
A lot of people seem to just use the example config file and run with it (causing issues with some default settings, like [node_size] medium)

If you are already assuming a medium sized node (yet running online_delete with a setting of just 2000) in the example configuration, adding a 50-100GB [shard_db] in there would make sense too. If people then run with the default config they automatically contribute to the decentralization and distributing the load of the network. Currently they seem to actually hurt it with the short online_delete interval...

**Comment by professorhantzen** [comment]
This is a great idea.

Additionally, providing a few different example configurations for various use-cases might help increase understanding of rippled's configuration options at the outset.  I suspect the reason most people go with the example config is because they don't have the necessary understanding to do anything else.

**Comment by miguelportilla** [comment]
Thanks for the great feedback. The example has been added: https://github.com/ripple/rippled/pull/2403
