### ISSUE TITLE
Ripple should gracefully recover from an unsynced node

### ISSUE THREAD

**Issue by DaveWK** [ripple/rippled#2417]
When attempting to sync the chain, I encountered:
NetworkOPs:WRN We are not running on the consensus ledger
and
LedgerConsensus:WRN Need consensus ledger: xxxx

From research it seems unless syncing from scratch, there seems to be a timer around how long rippled will attempt to sync up based around block height.

Additionally it seems the prevailing suggestion is to run ledger_cleaner by hand.. Why can't rippled retry grabbing confirmed ledgers it doesn't have on it's own without manual intervention?

**Comment by JoelKatz** [comment]
So long as you keep rippled running, it will keep trying to get, and stay, synchronized with the network. The ledger cleaner is used for clean up a corrupt or possibly corrupt database, possibly caused by abnormal termination or a similar problem. The server will try to fill in history and catch up without manual intervention.

The server's number one priority is to keep up with the live network. Its number two priority is to push a continuous stream of events and changes to its clients. Its number three priority is to fill in missing history as configured.
