### ISSUE TITLE
rippled account_info ledgerNotFound

### ISSUE THREAD

**Issue by kodmanyagha** [ripple/rippled#2442]
Sometimes rippled showing correct answer, sometimes not. I'm executing this command:

`rippled account_info rGBKzJqXJh5fNP7yyKxDGAXDbR4nzp5ruF true
`
Sometimes I'm getting this answer:
```
{
   "result" : {
      "account_data" : {
         "Account" : "rGBKzJqXJh5fNP7yyKxDGAXDbR4nzp5ruF",
         "Balance" : "25800000",
         "Flags" : 0,
         "LedgerEntryType" : "AccountRoot",
         "OwnerCount" : 0,
         "PreviousTxnID" : "3D98EE82342B3114A434DE425E60811FC4565F9B5CD51CE78E552F2C6CE97851",
         "PreviousTxnLgrSeq" : 37341484,
         "Sequence" : 1,
         "index" : "EACA2F40063BE7C6C2A6EB9FD0420C676EB2A8B21B41A4A4635428DCB0E44493"
      },
      "ledger_current_index" : 37359895,
      "status" : "success",
      "validated" : false
   }
}
```

Sometimes like this:
```
{
   "result" : {
      "error" : "noNetwork",
      "error_code" : 17,
      "error_message" : "InsufficientNetworkMode",
      "request" : {
         "account" : "rGBKzJqXJh5fNP7yyKxDGAXDbR4nzp5ruF",
         "command" : "account_info"
      },
      "status" : "error"
   }
}

```

I'm using NuDB database engine. Why I can't get correct result everytime? Where I'm making mistake? Thanks.

**Comment by ximinez** [comment]
That generally means that your rippled can not keep up with the network activity. It's not too unusual for it to happen every once in a while, but if you're seeing it enough to be annoying, then your node is having trouble keeping up with the network. There are a lot of things that could cause it, but since you're using NuDB the first thing to check is that your storage has enough IOPS. If you're not storing a lot of historical ledger data, (and if you have ample RAM) you may get better results with RocksDB. Other possibilities include, but aren't limited to, other processes on the machine bogging down the system, network saturation, and insufficient RAM.

**Comment by kodmanyagha** [comment]
Yes the problem is about IOPS. I installed rippled different server it has SSD and everything is fine now. Thanks.

**Comment by ximinez** [comment]
You're welcome. I'm going to close this issue.
