### ISSUE TITLE
BoringSSL support

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2464]
Similar to #2162, it would be nice to be able to use a non-OpenSSL library to link against rippled.

BoringSSL is a good candidate next to LibreSSL, since apparently it might have performance benefits (https://konradzemek.com/2015/08/16/asio-ssl-and-scalability/) and it is really easy to build and use with Bazel (compiling LibreSSL there is somewhat difficult and compiling OpenSSL is something one usually doesn't even want to try - besides Boost and the build toolchain, this is your only external dependency that you require to be already installed).

I ran into some issues (e.g. BoringSSL doesn't support RNG seed files and misses a few functions that you use), but nothing that seemed impossible.

While switching to exclusively BoringSSL is likely out of the question (a public internal Google fork is not something one wants to depend on), it would be a great alternative to have for performance and security reasons.

**Comment by nbougalis** [comment]
I am supportive of the effort to reduce our dependency on OpenSSL as much as possible. Outside of the use by `Boost` to have TLS support (which we'll have to accept), we don't use it extensively, and the existing uses _should_ be easy to change:

* With the random data API (`RAND_xxx`, isolated in [csprng.cpp](https://github.com/ripple/rippled/blob/develop/src/ripple/crypto/impl/csprng.cpp)). Rather than relying on OpenSSL or any library for this, I'd prefer we migrate to [Fortuna](https://en.wikipedia.org/wiki/Fortuna_(PRNG)).
* To perform some EC operations (mostly isolate in [crypto/impl](https://github.com/ripple/rippled/tree/develop/src/ripple/crypto/impl)). Most of those can (should) probably be migrated to the `secp256k1` library.

**Comment by MarkusTeufelberger** [comment]
Ok, looking a bit more into this:

* `EC_POINT_bn2point` is not available on boringssl, but it is only used in one single location in rippled when deriving a key from a seed. `secp256k` probably should have the necessary primitives I guess.
* There's a missing include in https://github.com/ripple/rippled/blob/d702e736ca1b445d29c9b9c96b2bd69ada449c0f/src/ripple/crypto/impl/openssl.cpp#L105 (`NID_secp256k1` is not part of any included headers, should be in `<openssl/nid.h>` on BoringSSL or `<openssl/obj_mac.h>` on OpenSSL).
* `RAND_write_file` is not available on BoringSSL. I'm not convinced this functionality is even necessary to have in rippled. If entropy sucks, it likely was bad before too and if it is already good then there's not much benefit gained from storing a file filled with random bytes.

These were the only compiler errors I got with BoringSSL, so it doesn't look insurmountable.

**Comment by cryptobrad** [comment]
The crud under `crypto` needs to go and unless someone else does it first I plan on ripping out mot of that and relying on the secp256k1 library directly.

**Comment by MarkusTeufelberger** [comment]
Closed with which resolution? No longer an issue or wontfix?

**Comment by nbougalis** [comment]
We rely on Boost which already has a dependency on OpenSSL. Given that, doing extra work to support another BoringSSL (especially since code changes to Boost.Asio are needed) seems counterproductive.

Also, considering that OpenSSL has improved support for elliptic curves and now supports Ed25519 also, I think we should strongly consider removing the Ed25519 and secp256k1 libraries from the codebase and using the OpenSSL implementation instead, reducing complexity and external dependencies.

So unless BoringSSL has similar support, adding it will just increase complexity. If BoringSSL becomes fully supported by Boost, has secp256k1 and Ed25519 support, and it’s available on all our platforms, we can revisit this issue.

If you prefer to re-open this issue, I’m fine with that.
