### ISSUE TITLE
-DBOOST_COROUTINE_NO_DEPRECATION_WARNING has no effect

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2486]
See title.

It might be worth a comment or two in the build files why you stick for years now with a deprecated library by the way.

**Comment by vinniefalco** [comment]
1. The macro was renamed to **BOOST_COROUTINES_NO_DEPRECATION_WARNING** (note the 'S')

2. This is not the fault of rippled, it is because the author of Boost.Context decided to deprecate a library that is in use by Boost.Asio

In my opinion it was a poor choice to deprecate a boost library used by another boost library, without consulting the other author to work out a migration path. The newer version of Boost.Context (called Boost.Context2) requires C++11, and thus incompatible with Asio which works with C++03.

**Comment by MarkusTeufelberger** [comment]
1. I know, both macros are being set, the one in the title is useless.
2. rippled is C++11/C++14 anyways, so Boost.Context2 might already be usable? Boost.Asio seems to have gained some C++11 features by the way (https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/overview/cpp2011.html), but I'm not deep enough into that topic.
