### ISSUE TITLE
Why not support smart contract

### ISSUE THREAD

**Issue by luleigreat** [ripple/rippled#2499]
I think that it is easy for rippled to support smart contract , just like ethereum.
Although rippled has integrated many functions like issuing a new coin, escrow ,multisign, etc, I think it's cool to develop smart contract on ripple network.

**Comment by MarkusTeufelberger** [comment]
Do you have concrete proposals?

Rippled/RTXP has some built-in "smart" (or maybe "dumb"?) contracts, but they are just configurable with parameters and not completely freely designable compared to e.g. Ethereum and their EVM.

Using the existing functions/features, it should already be possible to add external smart contract capabilities and provide unlocking mechanisms for e.g. Escrow objects on the ledger instead of forcing every validator to also run user supplied code and deal with gas limits etc.

**Comment by nbougalis** [comment]
Thank you @MarkusTeufelberger for that excellent response. I am closing this issue.
