### ISSUE TITLE
[CI] Only internal Ripple developers can view Jenkins logs

### ISSUE THREAD

**Issue by JoeLoser** [ripple/rippled#2527]
Problem:
It seems the Jenkins log files for each Jenkins build on a commit are hosted internally on Ripple networks. As such, an external contributor cannot view the logs.  While I haven't broken the build yet on a particular platform, I can see it being difficult to fix problems that may only arise on other platforms without being able to view the build log files.  [Here](https://ci.ops.ripple.com/job/scott-schurr-rippled/job/xrp-round-to-zero-log/4//artifact/clang.debug.unity.txt) is an example log file.

@mellery451 any suggestions on what to do in this case? I appreciate your work on https://github.com/ripple/rippled/pull/2520

**Comment by nbougalis** [comment]
@JoeLoser, first let me say that I appreciate the contributions. 

Yeah, unfortunately the current Jenkins setup is running on machines that are inaccessible. It frustrates us too, at times, because getting to the logs is a bit of a pain.

By the way, while this does suck, I'm also glad that it's become a pain point for others, because it means that the rate of external contributions to the codebase is on the upswing, which is awesome.

We are investigating options that allow us to either make the logs public, or the possibility of hosting the infrastructure so that it is publicly accessible.

I'm tagging / assigning this issue to @mellery451, who'll likely take point for now.

**Comment by JoeLoser** [comment]
@nbougalis no problem! I'm really glad to see the detailed feedback in code reviews from other Ripple developers, including yourself.  @seelabs has been very helpful in teaching me the ropes of the team's code style and feedback process.

Glad to hear this may get worked on soon.  In the long run, it will be great to have the logs available for external contributors; it was one thing I appreciated a lot when contributing to Folly given the wide compiler and OS support.  Sorry to give you more work @mellery451 :)

**Comment by Turbots** [comment]
Have you considered cloud services such as Travis CI or Codeship? IIRC they are free for opensource projects and quite cheap for private repositories

**Comment by nbougalis** [comment]
We used Travis in the past, but had a lot of issues with builds timing out or otherwise not completing, so we migrated to a private Jenkins instance.

We will be reevaluating all our options going forward.
