### ISSUE TITLE
[question] How to get the missing ledger hostory?

### ISSUE THREAD

**Issue by LuoRyan** [ripple/rippled#2563]
Hi, my data stream topo is:
**(app user)---<http request>---(koa2 server)---<websocket>---Rippled(Stock server)**

Do you know how to configure the rippled server to get historical ledger?
(I got this error from koa2 server "**Server is missing ledger history in the specified range**")

I use these commands, but there is no historical ledger in the server_info result.
rippled **ledger_cleaner** 38996182
rippled **ledger_request** 38996182

**Comment by LuoRyan** [comment]
koa2 is a  web framework for node.js ~~

I want to fetch missing ledgers, for example:
my rippled sever have "complete_ledgers": "38996184-38997236",
but I want to fetch ledger 38996183, how to get the missing ledger,I don't know how to do this?

**Comment by lcgogo** [comment]
change the fetch_depth in ripple.cfg larger than the [ledger you want] to [current ledger]. 
Then restart ripple and wait.

# [fetch_depth]
#
#   The number of past ledgers to serve to other peers that request historical
#   ledger data (or "full" for no limit).
#
#   Servers that require low latency and high local performance may wish to
#   restrict the historical ledgers they are willing to serve. Setting this
#   below 32 can harm network stability as servers require easy access to
#   recent history to stay in sync. Values below 128 are not recommended.
#
#   The default is: full

For example, you want to fetch ledger 5000 and now the current ledger is 20000, you should set the fetch depth MORE than 15000(=20000 - 5000). Because the current ledger is increasing at the same time when you are waiting.

**Comment by mDuo13** [comment]
Nowadays, this is documented better in the [Configure Full History](https://xrpl.org/configure-full-history.html) article.
