### ISSUE TITLE
Setup a local network and ripple nodes

### ISSUE THREAD

**Issue by joelcorporan** [ripple/rippled#2591]
Hi,

I'm running a test with ripple, and I was looking for a straight-forward configuration to set up a local ripple network with few nodes (around 5 to 10 nodes, it might increase in the future).  Is there anything that you guys can provide me with?

Thank you

**Comment by MarkusTeufelberger** [comment]
Do you mean starting an independent ledger or a clustered network of servers that track the public ledger?

The first approach is not really documented unfortunately, since it is quite rare and maybe also because Ripple doesn't want to encourage competing ledgers. Make sure to set `earliest_seq` correctly in the config file.

**Comment by joelcorporan** [comment]
No, I would like to do some testing locally. Nothing related to start my own thing. I don't have time for that. However, I would like to test the behavior of the nodes. I'm conducting an experiment for my class.

**Comment by MarkusTeufelberger** [comment]
There's a relatively nice community guide here: https://rabbitkick.club/rippled_guide/rippled.html

Otherwise you can take a look at the official documentation here: https://developers.ripple.com/manage-the-rippled-server.html

It would be great if you could also publish your findings and/or methods somewhere! :-)

**Comment by nbougalis** [comment]
I am closing this issue, assuming that the links provided above helped, @joelcorporan. Feel free to reopen, if necessary.
