### ISSUE TITLE
High Network Usage

### ISSUE THREAD

**Issue by enVolt** [ripple/rippled#2600]
I was checking the metrics for my Rippled node, and I was surprised to see the network usage. I couldn't find anything relevant in the Rippled doc or any other forum where I could land up after googling around it.

Here is the Network Out usage - 
<img width="919" alt="image" src="https://user-images.githubusercontent.com/5167147/41835241-89866838-7874-11e8-9b31-4570f4be8e5b.png">

It's peeking up to 5146868155450 bytes (~5 TB) in an hour. The average usage during non-peek is ~2,000,000,000 bytes (~1.50 - 2 GB). **Network In** has similar metrics -

<img width="869" alt="image" src="https://user-images.githubusercontent.com/5167147/41835393-087ecb76-7875-11e8-8d64-439d860e06a2.png">

I'm not running any validator node. Just using the node to read through all the ledgers (Get ledger and get all Transactions; plus withdrawals via submitting the signed transaction hash (1 per hour top))

The only change I've tried so far is to change the size of node to `tiny`.

Here is the rippled.cfg file that I'm using -
https://gist.github.com/enVolt/6d1adf0965e334683585416371455fbe

This has significantly affected the cost of bandwidth in our AWS billing. Since it is mentioned in the docs, that public nodes are not meant to be Production usage, we opted to run a server. I'm looking for the recommendations to reduce the bandwidth usage.

**Comment by MarkusTeufelberger** [comment]
Validation has nearly no impact on anything, it is just signing and publishing stuff your server already calculates instead of keeping it internal.

Do you have stats on which IP and port causes this much traffic? If not, you might want to start monitoring this, otherwise it is a bit hard to guess. "Get ledger and get all Transactions" sounds a bit suspiciously costly. Also if you need to read through all the ledgers, storing only 256 of them backwards and throwing everything away after ~2 hours ("online_delete 2000") might not be the best choice.

"Node size" mostly deals with how much data is cached and how much is fetched at the same time. If anything a "small" node might use more network traffic than a "large" one.

**Comment by enVolt** [comment]
I currently don't have stats on IP/Port. I've multiple addresses, for which I need to know if any deposit is taking place. Since once a ledger is received, it is processed immediately, it doesn't affect me if it's getting dropped later on.

My guess here is it's syncing too much data to / from it's peers. Is there any way that can be controlled (or I can put a max cap on outward traffic)

**Comment by MarkusTeufelberger** [comment]
You'd need to use your operating system's capabilities to limit traffic. You can also serve less history that you're storing to peers, but since you are already hosting very little history, this will probably not help much.

**Comment by nbougalis** [comment]
We are investigating excessive bandwidth. In the meantime, I'd recommend you reduce the number of peers you connect to:
```
[peers_max]
5
```
