### ISSUE TITLE
[QUESTION] Running a Private Rippled Testnet

### ISSUE THREAD

**Issue by alecuchiriac** [ripple/rippled#2634]
Hello! I am trying to run a private rippled testnet. I couldn't find any guides on the best practices to achieve that.

Currently, what I'm doing is running rippled in standalone mode locally on OSX with the '-a' argument when starting rippled, pointing towards the example cfg file. I can successfully get the account data of the genesis address, create new accounts by transferring xrp from the genesis address etc, getting ledger info etc.

To advance the ledger, I am running the following script:

`while true; do ./rippled ledger_accept --conf=/path/to/rippled.cfg; sleep 6; done`

This effectively accepts a new ledger every 6 seconds, and while it is fit for demo purposes at the moment, I feel like it wouldn't be the correct approach to deploy this on an AWS instance and try to run tests against that while making it act like the real testnet.

What I'm thinking is that I should set up a rippled server with maybe two or three validators, but I'm unsure how to run validators that would act on my standalone instance.

Down the line I also want to setup a faucet so other users could request xrp (just like the official testnet does), but that would be in the future.

Could anybody provide a couple insights or help me with setup instructions? Thanks a lot in advance!

**Comment by nbougalis** [comment]
Is there a reason why you aren’t using the publicly available testnet?

**Comment by AlexandruChiriac** [comment]
@nbougalis Thanks Nik for the reply! Please excuse me if I'm missing something really obvious, I am new to networking in general, but I am passionate and willing to learn more! The ripple protocol really fascinates me.

I am trying to setup a local private network so that I can go through the whole flow of moving XRP from the genesis address freely. I am writing a school project based on ripple and would like to be able to mimic the way the real network acts, only on a much much smaller scale.

With my current understanding, I have to run a validator first, get its public key and add it in the [validators] field of the second node I want to spin up. Please correct me if I'm wrong.

Here's my validator node rippled.cfg file:
`
[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 5005
ip = 127.0.0.1
admin = 127.0.0.1
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

#-------------------------------------------------------------------------------

[node_size]
medium

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

# Where to find some other servers speaking the Ripple protocol.
#**Here I am very uncertain what I should put, in order to start it separetly**
[ips]
192.0.0.1 51235


[validators_file]
validators.txt

[validation_quorum]
1

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1

[validator_token]
#********
`


and the validators.txt:
`
[validators]
#itself
`

**Comment by AlexandruChiriac** [comment]
@nbougalis Thanks Nik for the reply! Please excuse me if I'm missing something really obvious, I am new to networking in general, but I am passionate and willing to learn more! The ripple protocol really fascinates me.

I am trying to setup a local private network so that I can go through the whole flow of moving XRP from the genesis address freely. I am writing a school project based on ripple and would like to be able to mimic the way the real network acts, only on a much much smaller scale.

With my current understanding, I have to run a validator first, get its public key and add it in the [validators] field of the second node I want to spin up. Please correct me if I'm wrong. I am uncertain what I should put under the [ips] section.

Here's my validator node rippled.cfg file:
```
[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 5005
ip = 127.0.0.1
admin = 127.0.0.1
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

#-------------------------------------------------------------------------------

[node_size]
medium

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=2000
advisory_delete=0

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

#Where to find some other servers speaking the Ripple protocol.
#**Here I am very uncertain what I should put, in order to start it separetly**
[ips]
192.0.0.1 51235

[validators_file]
validators.txt

[validation_quorum]
1

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1

[validator_token]
#*****
```

and the validators.txt:
```
[validators]
#itself
```

**Comment by treisto** [comment]
"What I'm thinking is that I should set up a rippled server with maybe two or three validators, but I'm unsure how to run validators that would act on my standalone instance."

@alecuchiriac How did you solve this please?

**Comment by JoelKatz** [comment]
I think it's as simple as making sure they only connect to each other and configuring them with only each other as validators. I can't think of anything else you need to do offhand.
