### ISSUE TITLE
Why payment channel and escrow only support XRP, what if it supports issued currency?

### ISSUE THREAD

**Issue by luleigreat** [ripple/rippled#2658]

**Comment by luleigreat** [comment]
We want to escrow some issuing currency ,but found that escrow only support xrp. What if I change the code to support issuing currency?

**Comment by nbougalis** [comment]
We can’t stop you from changing the code to add such support, or from campaigning to get the amendment associated with your changes approved. If you want to submit a pull request, to include your changes in our release branch that would be cool and we would certainly review your code and consider it for inclusion.  

But the change you are suggesting is quite extensive and is not as cut and dry. Please consider that unlike an XRP escrow, where the XRP itself is being held within the escrow object and there is no counterparty, an IOU escrow involves a counterparty and  represents an obligation of the that counterparty.

You will need to provide a mechanism that allows issuers to explicitly opt in to allowing their issuances to be escrowed and to decide how other, existing, features interact with IOU escrows.

Also challenging, such an object will need to thread against _three_ accounts: the sender, the receiver and the issuer. No such support exists at this time, and adding it will likely require low-level changes.

This is certainly a challenging modification. Beyond the technical, I think that the semantics of an IOU escrow would be somewhat surprising to people, and that will be the bigger challenge.

**Comment by MarkusTeufelberger** [comment]
As far as I understand Escrow, it is just a semi-automatic way to have funds sent somewhere after some timestamp has passed and/or to have a way to encode branching into a transaction ("If X gets revealed by Y then Z, otherwise Cancel"). I'm not sure why this would be unexpected functionality just because the currency that is transacted that way is not called XRP or because the base asset is held by a third party instead of nonexistent (XRP just stand for themselves).

There are some immediate concerns coming to my mind around freezing, (changing) issuer fees and QualityIn/QualityOut settings as well as a potential receiver not having enough "room" in a trust line for additional IOUs. I suspect IOU Escows actually might only be allowed to release into Checks instead of directly releasing funds into target accounts.

I don't see why issuers would have to opt in to have their issuances Escrowed, after all the same functionality could be provided invisible to XRPL off-chain too by handing limited control of an account to a smart contract. Unlike Freezing I would rather see IOU Escrow being implemented as "issuer opt-out" and "default on".

All in all I think IOU Escrow might be possible and I can see a lot of use cases for it actually, I wouldn't rank it as top priority on my wish list though - IOU PayChan for example would be ranked higher. This is of course just my opinion and it would be awesome to see a more concrete design for IOU Escrow. As Nik said though, it is definitely a challenge.

**Comment by nbougalis** [comment]
@MarkusTeufelberger, a couple of thoughts:

>I don't see why issuers would have to opt in to have their issuances Escrowed

Issuers should be able to quickly sum up their _total obligations_; they do so by examining all the trustlines associated with their account.

Escrowed funds would not be kept in a trust line, but in the escrowed object itself, which means that, without the ability to opt-out, issuers would be, at a minimum, be forced to make changes to their accounting systems if this amendment were activated.

Interaction with existing IOU-specific features is also challenging, as we both pointed out.

**Comment by MarkusTeufelberger** [comment]
Depending on the design, an Escrowed IOU could consist of both an Escrow object that contains the escrow related settings and a RippleState (towards the Escrow object) that contains the balance related stuff. That way iterating over RippleState objects would still give the correct, total outstanding balance - the downside is that it is now ~twice as expensive data wise than an XRP only escrow.

**Comment by luleigreat** [comment]
@nbougalis I have made a change in my code and it works fine except for that  total obligations is not easy to sum up.

I applied the change and just update on a chain without Escrow transaction before，there's no problem. I know that if I change on the public chain, it must be done with a new feature.

So,  do you have some suggestions for summing up total obligations ?  If I add every escrow to Issuer's dir, it seems not so elegant.

**Comment by luleigreat** [comment]
@MarkusTeufelberger thanks for your 'immediate concerns',  I will think more deeply about it.

**Comment by nbougalis** [comment]
If you can push your changes to a branch on GitHub and give me a link, I’d be happy to take a look at what you did.

**Comment by luleigreat** [comment]
@nbougalis I had tried to push my branch. But failed, seems I don't have the right ?

Git outputs:
$ git push --set-upstream origin feature/escrowForIOU
Enter passphrase for key '/c/Users/Jerry/.ssh/id_rsa':
ERROR: Permission to ripple/rippled.git denied to luleigreat.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists

**Comment by intelliot** [comment]
@luleigreat On GitHub, the typical workflow is for you to create a fork (click the `Fork` button at the top right) and then push to your fork. You can use [`git remote add`](https://git-scm.com/docs/git-remote) to add your fork as a remote.

You can then create a Pull Request (PR) at https://github.com/ripple/rippled/compare (click `compare across forks`).

**Comment by luleigreat** [comment]
Thanks very much @intelliot .
I have successfully made a pull request.

**Comment by nbougalis** [comment]
Thank you for opening PR #2672, @luleigreat! I'm going to close this issue and we can continue the discussion there.
