### ISSUE TITLE
Relax Boost Dependency

### ISSUE THREAD

**Issue by movitto** [ripple/rippled#2669]
While running through the process of building rippled on [Fedora 28 ](https://www.xrpchat.com/topic/26502-building-rippled-on-fedora-28/) we discovered the version of the boost dependency is seemingly too stringent. When we relaxed it from 1.67 to 1.66 (the version currently shipping with Fedora), the project still built successfully and we didn't have to download and build the boost libraries ourselves.

Can this dependency be relaxed in CMakeLists.txt? (we can send a PR if this is acceptable)

**Comment by MarkusTeufelberger** [comment]
I think this is not possible since boost::beast had some security fixes afair:
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/release_notes.html

**Comment by movitto** [comment]
Ah good to know, @MarkusTeufelberger thanks for the info. It doesn't seem that boost 1.67 is even available in [rawhide](https://koji.fedoraproject.org/koji/packageinfo?packageID=1074) yet so we'll have to try to get it working against a custom build of boost. When we tried last, the linker seemed to be tripping up over missing symbols, which I believe to be due to a mixup with the system boost and the locally compiled one. Perhaps if done from a fresh install, before boost is installed systemwide, it'll work as planned. Will keep this updated as we try, thanks again!

**Comment by movitto** [comment]
BTW somewhat related (since boost::beast was mentioned). Could someone provide some insight into the rationality behind & use of the seemingly vendored 'beast' logic under [src/ripple/beast](https://github.com/ripple/rippled/tree/develop/src/ripple/beast).

While exploring the rippled codebase we noticed that this directory contains modules which reference the vinniefalco/Beast project:
`"This file is part of Beast: https://github.com/vinniefalco/Beast"`

Yet from our understanding that repo is now deprecated and Beast is part of Boost proper (and is referenced above wrt the security fix). Furthermore the src/rippled/beast subdir seems to be being maintained with [commits](https://github.com/ripple/rippled/commits/develop/src/ripple/beast) from outside the upstream vinniefalco & boost codebases.

Any insight would be much appreciated.

**Comment by mellery451** [comment]
@movitto FWIW I just successfully built on fedora28 using a custom boost 1.67 build. On thing to consider: by default we will try to link to openssl, boost, protobuf and libc++ statically, therefore you  need the static lib packages for those dependencies (I had to install them on my system). Alternatively, you can pass `-Dstatic=OFF` when configuring cmake and we'll use the dynamic libs for those.

**Comment by MarkusTeufelberger** [comment]
I have a repo at https://github.com/MarkusTeufelberger/rippled-distrotest that tries to build rippled bleeding edge versions with distro native libraries only on travis and it doesn't look good at the moment in general (the ones failing even though they have boost 1.67+ fail because static is the default now which is something a lot of distros do not support - especially for critical libraries like openssl). As you already found out, Fedora rawhide is 8 months behind on its packaged version of Boost. Your best bet for distro native builds is the upcoming Ubuntu 18.10, maybe Alpine will work in the future too once the code here is fixed (the compatibility patches for musl have gotten much smaller already), Arch is also mostly working usually, except for static libraries which have been banned from the whole distro.

Beast used to be a helper abstraction library by the author of boost::beast who worked for Ripple. The http handling part of "ripplebeast" became boost::beast over time then when he decided to re-use that name.

**Comment by movitto** [comment]
@mellery451 @MarkusTeufelberger sorry for the belated response (though I suspect ya'll will like what I'm working on next). I just confirmed that rippled compiles as detailed under Fedora 28 w/ the system-wide boost libraries are installed. Not sure what the cause of the previous errors, will just chalk it up to a env-specific discrepancy ([that feel when](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvoWbs9kf_2UlthkgNmr5ns_34aO-HWueXBC0w3u1jlIA_XmTv) you can't reproduce an issue you had earlier...). 

Thanks for the info WRT the $issue and the beast module. Will update the doc on xrpchat momentarily.
