### ISSUE TITLE
lsfRequireDestTag change request

### ISSUE THREAD

**Issue by Crypto2** [ripple/rippled#2708]
Hello,

One great change for exchange/wallet providers would be to change lsfRequireDestTag so not only does it require a tag but the tag can't be 0. We have a lot of issues with this of people and I guess other exchanges sending a tag of 0 when the buyer doesn't include one instead of leaving it out of the TX altogether.

**Comment by MarkusTeufelberger** [comment]
Ideally, a set of acceptable DestinationTags would be supplied, but storing **that** on-ledger is a bit of a heavy burden...

Just requiring a positive nonzero int32 is probably not enough, since it would probably just trigger payments to fail and then these exchanges and wallet providers figure out that sending a 1 instead of a 0 makes the payments "work" again.

The current "blockchain" solution would be to store the set of acceptable tags on IPFS and just adding that hash to the ledger. IPNS would make it cheaper and less spammy on-ledger to change it, but could lead to concurrency issues if validators get different sets, so it probably would be easier to stick to the 1:1 hash:data model. I'm not so sure if I like that idea, it sounds a bit like a crutch to me.

**Comment by Crypto2** [comment]
yeah they might, would hope exchanges wouldn't be that ignorant though; but I guess that may be why they started sending 0 lol. Like we check each address for the lsfRequireDestTag and cancel the withdrawal if it is set and no tag was provided which is what all exchanges/wallets should do imo.

I would definitely say storing a list on blockchain wouldn't be good since there can be hundreds of thousands or millions of valid tags.
