### ISSUE TITLE
Inconsistency between `server_info.complete_ledgers` and `tx` method.

### ISSUE THREAD

**Issue by 3rdstage** [ripple/rippled#2724]
Rippled API documentation of [`server_info` ](https://developers.ripple.com/server_info.html) explains that `complete_ledgers` is 

> Range expression indicating the sequence numbers of the ledger versions the local rippled has in its database.

But when I reviewed the complete_ledgers with my 4 nodes (3 validators + 1 trackers, `rippled` 1.0.1) private Ripple network (not connected with public Ripple network), things were different.

After a few restarts of tracker node, the `complete_ledgers` from `server_info` command showed starting(the lowest) ledger index more than 1,000,000  although the tracker is configured to have full ledgers via `[ledger_history]` of `rippled.cfg`.  
At this time, the other 3 validators also show much less range of complete ledgers. In other words, the starting ledger indexes of validators are much larger than that of  tracker node.  

In this situation, calling [`tx`](https://developers.ripple.com/tx.html) method for a ledger before the starting index of tracker's `complete_ledgers` is expected to return empty result or error, considering the above definition of `complete_ledgers`, cause there all complete ledgers are after the ledger containing the queried transaction.

But, with my above 4 node private network, the `tx` call return normal and full results.  That means it seems that the node or network has ledgers outside(before) the range described by `complete_ledgers`.

So, at least for rippled 1.0.1, `complete_ledgers` shows something else considering `tx` method.

**Comment by ximinez** [comment]
Here's the most important bit of information:

> After a few restarts of tracker node, 

After restarting a node, rippled has to check which complete ledgers it has in the node store. This is done in the background at low priority. Therefore, it can take quite some time, especially if you're filling a large gap - such as a million ledgers. If you monitor the `completed_ledgers` for a while, you should see the lower bound gradually decreasing, and if you give it enough time, it should get back down to your starting ledger.

The reason the `tx` command works is because it can use the transaction hash to go directly into the node store to find the transaction data. Other commands which depend on a ledger index will be more likely to return an error.
