### ISSUE TITLE
JSON-RPC subscribe method not working properly

### ISSUE THREAD

**Issue by assafadar** [ripple/rippled#2729]
Hey all, 
Recently I installed rippled 1.1.0 private server and I am building an app that will allow XRP payments.
When performing a subscribe request (trough RPC and not web socket) I am getting notifications for pretty much everything. 

I submit an array of my accounts (the one's I want to be notified about) but for some reason I am getting notifications for many more accounts... 

This is my subscribe request:

{"streams":["transactions"],"id":"notfications","accounts":[accountsArr"],"url":"callBackURL"}

This code worked for my in the previous version of rippled. 

BR,,

**Comment by intelliot** [comment]
(Copied directly from https://groups.google.com/d/msg/ripple-server/p8XBaHnIcmc/38_VlkXSBgAJ)

You are requesting the "transactions" stream, which sends a message whenever any transaction is included in a closed ledger. Since you already specifying "accounts", you can remove the "streams" parameter from your request.

Example:

{"id":"notifications","accounts":["rrpNnNLKrartuEqfJGpqyDwPj1AFPg9vn1"],"url":"callBackURL"}

By specifying "accounts", rippled will monitor those accounts for validated transactions. The server sends a notification for any transaction that affects at least one of these accounts.

**Comment by nbougalis** [comment]
I'm closing this issue, assuming that @intelliot's response addresses your question. If you have anything further, please feel free to reopen this issue or create a new one as necessary.
