### ISSUE TITLE
How to get the finial hash in  the parallel multi sign 

### ISSUE THREAD

**Issue by readygo586** [ripple/rippled#2782]
in https://developers.ripple.com/send-a-multi-signed-transaction.html, it said "
 If you collected the signatures in parallel, you must manually construct a tx_json object with all the signatures included. Take the Signers arrays from all the sign_for responses, and combine their contents into a single Signers array that has each signature. **Add the combined Signers array to the original transaction JSON value**." 

I follow the instructions and try to multi sign in parallel.

step1: generate  the transaction
<img width="762" alt="image" src="https://user-images.githubusercontent.com/41469645/48823373-93315e00-ed9b-11e8-864c-96f0cea135b0.png">

step2: sign with the  signer1.
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/41469645/48823397-aba17880-ed9b-11e8-9409-bfccfd634996.png">

step3:  sign with the signer2. 

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/41469645/48823434-cbd13780-ed9b-11e8-8de6-9ee72d2d149b.png">

step4: combine signers,  but there is no hash result. 
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/41469645/48823461-e2778e80-ed9b-11e8-9cf0-33ed09544b1a.png">

How can I get the finial hash?

**Comment by nbougalis** [comment]
Thanks for opening this issue. We will get back to you later today!

**Comment by MarkusTeufelberger** [comment]
In the final combined result the signing pubkey is the same for both signers...

**Comment by readygo586** [comment]
@MarkusTeufelberger,  Thank you for figure out, I fix this same signing pubkey problem.

**Comment by readygo586** [comment]
Now I generated the finial hash locally, and submit to testnet,  It shows invalid signature as below.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/41469645/48851469-1c6d8280-ede6-11e8-9a21-f314df59a195.png">

**Comment by readygo586** [comment]
One  more question, should I disable the _master key and regular key_ before applying the multisign feature in this account?

**Comment by scottschurr** [comment]
I need to ask a clarifying question.  In the original problem statement in steps 2 and 3 you write **"sign with"**.  What _specifically_ did you call in order to get those signatures?  Signatures for multisigning are calculated slightly differently than non-multisigning signatures.  Did you call `sign_for`, which would give you the correct answer, or did you call something else?

If you call `sign_for` then the result is returned in this format:
```
         "Account" : "rDg53Haik2475DJx8bjMDSDPj4VX7htaMd",
         "Amount" : "1000",
         "Destination" : "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
         "Fee" : "30",
         "Flags" : 2147483648,
         "Sequence" : 3,
         "Signers" : [
            {
               "Signer" : {
                  "Account" : "rPcNzota6B8YBokhYtcTNqQVCngtbnWfux",
                  "SigningPubKey" : "02FE36A690D6973D55F88553F5D2C4202DE75F2CF8A6D0E17C70AC223F044501F8",
                  "TxnSignature" : "304302207AE42DDA3221B44F1CB248AED6E0AA0A8341D3A42BE6D5EB172384A618DF5F51021F7DFB7343A3B526B83BC304D16FF46AA176E0D3BDF725EA3E6FA11D8DA846E8"
               }
            }
         ],
         "SigningPubKey" : "",
         "TransactionType" : "Payment",
         "hash" : "7EF6377889E2412080A98A581D2D8D2815E65C2A7524FE144BC9B0709180E45E"
```
That's not what is shown in your steps 2 and 3.  So I suspect you're not calling `sign_for`.

Hopefully you are using a local rippled instance to get your signatures.  I'm not saying you aren't, but just in case, please don't submit secrets across a public network in order to get signatures.  If you do not have a local rippled instance, and you can build C++ code, then you might consider using the ripple-offline-tool: https://github.com/ximinez/ripple-offline-tool

Now let's talk through whether you should "disable the master key and regular key before applying the multisign feature".

The way you "apply the multisigning feature" is by submitting a `SignerListSet` transaction to the network.  That transaction must be signed.  Since the account is not yet multisigning (since it doesn't have the `SignerList` yet) you must sign that transaction using either the master key or the regular key.

Once the account is successfully set up with multisigning, and you've verified that you can successfully multisign a transaction for that account, you can at your discretion disable the master key and/or remove the regular key.  But please verify that you can successfully multisign before you do so.

I hope that helps.

**Comment by readygo586** [comment]
@scottschurr Thank you for your clarification. 
Now I am developing ripple's multi-sign based on  _https://github.com/rubblelabs/ripple_, it only supports non-multisign currently.
In my implementation,  I repeated non-mulitsign with different 2 secrets, then combine 2 signatures together, which shown in step2-step4.

**Comment by scottschurr** [comment]
Right.  I don't know anything about what's happening in rubblelabs, so I think I've done all I can for now.  You'll need for them to support multisign if you want to use their stuff.

If your questions are answered it would be great is you would close the issue.  Best of luck.

**Comment by readygo586** [comment]
@scottschurr As you mentioned " Signatures for multisigning are calculated slightly differently than non-multisigning signature", where can I find document about this? or which file in rippled I can refer to?

**Comment by readygo586** [comment]
@scottschurr very thanks for your clear step by step information. Now I successfully get the TxnSignature locally. Then the question back to  original one.

How can I get finial hash if I multisign in parallel?

**Comment by scottschurr** [comment]
@readygo586, Written communication is tricky. I'm not at all sure what you're trying to do or accomplish.  But I'll make a guess.  Please clarify, preferably with an example, if I don't answer the question you intended to ask.

First, a question you didn't ask but you need to know about.  Once the various signatures have been computed they need to be collected into the transaction as you have shown.  What is not necessarily obvious is that the signatures in the final transaction must be **sorted** (numerically, not alphabetically) by the account ID.  If you submit a multisigned transaction where the signatures are **not** sorted the transaction will be rejected.  Here's an example where that sort takes place: https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/impl/TransactionSign.cpp#L861-L866

Once you have the fully formed transaction with all the (sorted) multisignatures, then getting the hash of that transaction is no different from getting the hash of any other transaction.  Here's a place in the code where the hash of a transaction is being computed:

https://github.com/ripple/rippled/blob/develop/src/ripple/protocol/impl/STTx.cpp#L66

And here is where the serialized data is assembled for the transaction hash computation:

https://github.com/ripple/rippled/blob/develop/src/ripple/protocol/impl/STObject.cpp#L294-L300

Possibly that answers your question?

**Comment by readygo586** [comment]
@scottschurr very thanks.  These 3 information are all I need.

**Comment by scottschurr** [comment]
@readygo586, if you're questions are answered it would be great if you could close this issue.  Thanks.
