### ISSUE TITLE
Does the testate support sign_for command?

### ISSUE THREAD

**Issue by readygo586** [ripple/rippled#2785]
Step1: I setup the SignerListSet for _rKqrEZztNygr7Puc2AUoyjeEFjbdqLHnmQ_ , querying shows such config  valid, shown as below.
 
<img width="867" alt="image" src="https://user-images.githubusercontent.com/41469645/48880012-6a67a200-ee49-11e8-9001-ccda4d624516.png">

<img width="870" alt="image" src="https://user-images.githubusercontent.com/41469645/48880027-7a7f8180-ee49-11e8-964f-2c3b7b72f73a.png">

Step2: I try to test the sign_for method in testnet as below. But the response show **not support**.
 

<img width="876" alt="default" src="https://user-images.githubusercontent.com/41469645/48879904-f200e100-ee48-11e8-836b-7f91de187549.png">

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/41469645/48879957-296f8d80-ee49-11e8-81dd-6c3cce2a7ba8.png">

### **So, does  the testnet support sign_for method?**

**Comment by intelliot** [comment]
Yes. Transaction signing is a feature of rippled; it is not related to the testnet. You can run rippled and use your own rippled server (instead of connecting to `s.altnet.rippletest.net`). You can also connect your rippled server to the testnet.

Since rippled v1.1.0, `sign` and `sign_for` are admin-only methods. You can run admin commands by connecting to your own rippled server. Alternatively, you can use a separate signing tool, like [ripple-libpp](https://github.com/ripple/ripple-libpp) (C++) or [ripple-lib](https://developers.ripple.com/rippleapi-reference.html#sign) (JS).

See also:
- https://developers.ripple.com/enable-public-signing.html
- https://github.com/ripple/rippled/pull/2657

**Comment by readygo586** [comment]
@intelliot  
Very thanks.
