### ISSUE TITLE
NetworkOPs:WRN We are not running on the consensus ledger

### ISSUE THREAD

**Issue by qiluge** [ripple/rippled#3012]
hello, my ledger height cannot inceate at mainnet sync node, and the warnning is ```NetworkOPs:WRN We are not running on the consensus ledger```, please help me to resolve this problem, thanks!
![image](https://user-images.githubusercontent.com/19525062/62098904-e8285b00-b2be-11e9-9c89-2c270decd29a.png)

**Comment by mDuo13** [comment]
Your server should automatically sync to the network within the first 5-15 minutes after starting it up. During that time, `NetworkOPs:WRN We are not running on the consensus ledger` errors may appear but are benign. (Note to self: add that to [Understanding Log Messages](https://xrpl.org/understanding-log-messages.html).)

If you still get these errors after syncing or your server is not synced after ~15 minutes, then that is a problem. Sometimes, you can get the server to sync just by restarting it once. If that still doesn't work, common causes of this problem are:

- Hardware not meeting the [system requirements](https://xrpl.org/system-requirements.html), especially RAM and disk I/O.
- Network connection not fast enough or not reliable enough to stay synced.
- Misconfiguration (for example, storing the databases on rotational disks instead of the SSD storage)

**Comment by qiluge** [comment]
Thank you very much, my node has already normal sync after a while.

**Comment by marioBZ7** [comment]
What if my AWS EC2 ran out of disk space and I had to add another volume increase the capacity? My EC2 is not syncing. 

Thanks!
