### ISSUE TITLE
How do you create a JSON file to import? [import_db]

### ISSUE THREAD

**Issue by h6dworker** [ripple/rippled#3035]
How do you create a JSON file to import?

No method found for [import_db].

Please support.

https://xrpl.org/configure-full-history.html
https://xrpl.org/commandline-usage.html

**Comment by mellery451** [comment]
There is no json involved in import - it's reading/writing node-store database files directly. The `[import_db]` config section along with the `--import` command line flag are used to import an existing node-store database into your configured node store (specified in the `[node_db]` config section). This is typically used as a one-time step when copying or moving data from another server. You can see that in step 7 of the configure-full-history document it mentions invoking `rippled` with the `--import` option in order to copy the data specified in the `[import_db]` config section.

**Comment by h6dworker** [comment]
Thank you for your quick reply.

Does this mean that the current module can read NUDB!?

I saw the procedure to read "JSON text file" before.
I thought I would read JSON text.

Sorry for making a fuss.

**Comment by mellery451** [comment]
Yes, the import process should be able to read/write any of the supported backends - which currently is NuDB (recommended) or RocksDB. I believe the import process could also be used to migrate from one to the other. I'm looking at the docs and still not sure which JSON command you are thinking of...maybe `--ledgerfile` ? If it is that command you are thinking of, then it's really only used for debug/test scenarios and doesn't really have a valid use-case on the live network. If there is some other part of the documentation that needs clarification, feel free to open another issue. Thanks.

**Comment by MarkusTeufelberger** [comment]
> doesn't really have a valid use-case on the live network

The valid use case would be to restart a (network of) validator(s) without a nodestore from a known good state or to orchestrate a hard fork.

**Comment by h6dworker** [comment]
It is certainly so`--ledgerfile`.
https://github.com/ripple/ripple-dev-portal/blob/master/content/_code-samples/rippled-cli/ledger-file.json

Thank you for teaching me carefully.
