### ISSUE TITLE
Include rippled version in validation

### ISSUE THREAD

**Issue by mayurbhandary** [ripple/rippled#3071]
It would be useful to know what version the server is running when it issues a validation.

**Comment by MarkusTeufelberger** [comment]
What would be your use case?

If it is added somehow, this information can't be verified anyways by the way.

**Comment by nbougalis** [comment]
The information would be in the signed portion of the validation. If a validator wants to lie they can and there's nothing we can do to stop them; but why would they?

As for what, having the information available in a validation will make it easier for anyone to collect and report on metrics about what version of the software validators are running. Having this information is useful and can affect decisions that validator operators take.

**Comment by MarkusTeufelberger** [comment]
> If a validator wants to lie they can and there's nothing we can do to stop them; but why would they?

Because telling everyone exactly which version of a software you're using increases your attack surface. It also leaks information about your operating procedures (e.g. how fast + when you update after a new software release). It also increases traffic network wide.

Maybe there could/should be an option for some kind of arbitrary "memo" key/value pairs attached to validations, but I'm not so sure if software version is a useful field there. Some other things that validators might want to communicate (though I'm not sure if that's really necessary to do with every single validation) include: jurisdiction of operator, jurisdiction of server hosting provider, some more general info about the operator...

All of these might be interesting to have signed and broadcast periodically, though ALL of these are much better off in a https://xrpl.org/xrp-ledger-toml.html file.

**Comment by mayurbhandary** [comment]
Hi Markus, you bring up some very valid concerns. Another option is to use a proto buffer message that contains the server's public key, version number, etc. This would only be sent once when a peer connects and reduce the impact on network traffic.  Broadcasting the version number in this way would not increase the attack surface since there are other ways for malicious actors to get the version number. The issue with including version number in the .toml file is that it will become out of date quickly. I do agree that things like jurisdiction should be included in the .toml.

**Comment by MarkusTeufelberger** [comment]
You should not be able to connect directly to a validator and if you do you should definititely not be able to know that this is a validator you're connected to. I thought you wanted to know the software version of validators, not random nodes on the network? They are anyways already visible in the /crawl endpoint, so no need to send this in the peer protocol too...

The .toml file should be actively maintained and a responsible operator would anyways not just auto-update but have a certain process. Programmatically updating a file can certainly be part of such a process.

**Comment by nbougalis** [comment]
>You should not be able to connect directly to a validator and if you do you should definititely not be able to know that this is a validator you're connected to.
I don't know that I agree. Certainly, locking down a validator by limiting who can connect to it is a prudent security step that an operator can take (and one I recommend), but it's by no mean a requirement.

Furthermore, if onion-routing of proposals and validations is implemented, this argument becomes somewhat moot, since the validations will "emerge" at another part of the network, and you can't know if the server broadcasting it is the source or the relay.

>The .toml file should be actively maintained and a responsible operator would anyways not just auto-update but have a certain process. Programmatically updating a file can certainly be part of such a process.
Agreed, but I think that if we can automate something within the protocol in a lightweight and unobtrusive manner, eliminating the need for a third-party service, then we probably should do that.
