### ISSUE TITLE
Fatal error—possible database corruption?

### ISSUE THREAD

**Issue by mDuo13** [ripple/rippled#3078]
As [reported on XRPChat](https://www.xrpchat.com/topic/32891-rippled-131-stock-node-fatal-exception/) by @gnanderson, one of his servers is consistently crashing. The errors make it seem like a database corruption issue, but just in case:

>  On one of my stock nodes I'm seeing fatal exception every 30-60 seconds or so & daemon restart  - looks like maybe DB corruption but thought I'd post this here to see if anyone has seen something similar before? 
> 
>     2019-Sep-12 14:26:48.244803814 SHAMap:WRN Corrupt node received
>     2019-Sep-12 14:26:49.957015801 Peer:WRN [067] onReadMessage from XXXX at x.x.x.x:40003: stream truncated
>     2019-Sep-12 14:26:50.404850371 NetworkOPs:WRN We are not running on the consensus ledger
>     2019-Sep-12 14:26:51.307654091 NodeObject:FTL Exception, lz4 decompress: LZ4_decompress_fast
>     2019-Sep-12 14:26:58.493346589 Application:NFO process starting: rippled-1.3.1

I agree it looks like database corruption, but maybe someone who knows this section of the code can take a closer look just in case?

If it is in fact a corruption issue, I can add it to the docs on logs. Of course, it would be great to know how the database got corrupted, but all kinds of random hardware things can contribute to that so it may not be possible to figure out.

**Comment by gnanderson** [comment]
Thanks @mDuo13 - Initial investigations: 

- The data volume where the rippled database resides on for this node is backed by a pair of NVME SSD drives configured as software raid1 (Linux MD).
- Raid status is good

Manual intervention of stopping the rippled daemon, removing the database, and restarting rippled has bee unsuccessful. The problem re-occured quite quickly (at least within 30 minutes).

The type of SSD is Samsung TLC V-NAND with Polaris era controller, reasonable but _definately_ consumer grade SKU's; with one of them reporting significantly higher lifetime wear leveling usage via smartmon tools.

Because the problem re-occured fairly quickly after manually removing the database, and the higher usage stats of one of the raid pair, I think it's reasonable to suspect an SSD hardware issue is the cause of this.
