### ISSUE TITLE
Trailing comments `#...` in rippled config lines aren't handled

### ISSUE THREAD

**Issue by mellery451** [ripple/rippled#3121]
...currently trailing comment text probably gets interpreted as a value or some such thing and in-fact they just need to be stripped away before any real parsing.

**Comment by alloyxrp** [comment]
A line which has a trailing comment gets ignored completely.

**Comment by scottschurr** [comment]
I think the actual state of the world is a little worse than that.  If I remember correctly, it depends on the other content of the line as to what effect the trailing comment has.

**Comment by mellery451** [comment]
Proposal: 
1. allow trailing comments on all config files lines (`#` marks the start of a comment anywhere on a line).
2. if you need a literal `#` in one of your fields/lines, escape the `#` with a `\`. (the only field types that could even possibly need a `#` might be passwords or file paths ?)
3. If any trailing comment is detected in a current config, emit a warning to the log letting operators know that the behavior with respect to trailing comments has changed. This warning would be removed in a subsequent release.  

Thoughts?

**Comment by scottschurr** [comment]
I'm not keen on escaping literal `#` in lines that need it.  Escapes get really messy because you need to set up ways to escape the escape.

I'd like to suggest an alternative that I got from from @bachase:

- As you parse the config file check every line to see if all characters are consumed.  Only if there are leftover trailing characters...
- Check if the leftover characters look like a comment (optional whitespace followed by a `#` optionally followed by other characters).
- If the leftover characters look like a comment then ignore the comment and proceed.
- If there are leftover characters that don't look like a comment, then echo a diagnostic message to the console, stop parsing, and close rippled.

Some types of lines consume the entire line.  Examples are key/value pairs for passwords and file paths.  If we use the approach I suggest it will never be possible to add trailing comments to these lines.  But it's valid to put the comment on the previous line in these few cases.

The suggested approach has the advantage that people will not need to edit their config files to escape any required `#'` characters.

**Comment by MarkusTeufelberger** [comment]
How about using an existing library to parse config files in some standard format (ini, yaml, toml...)? Surely this is not a unique problem...

**Comment by movitto** [comment]
> How about using an existing library to parse config files in some standard format (ini, yaml, toml...)? Surely this is not a unique problem...

@MarkusTeufelberger technically rippled.cfg isn't ini as comments in the former are marked by '#'s and ';' in the later

https://en.wikipedia.org/wiki/INI_file#Comments_2

There are a few libraries in this domain we could use. I worked on this in a previous life: http://augeas.net/

Contains a DSL to describe config file formats and could even be used for utility tooling to write to config files.

**Comment by mellery451** [comment]
@scottschurr we don't currently "parse" the config file using types..it's all strings. The interpretation of those strings is left of to the various classes that care about a config section. That would make the approach you suggest much harder to implement since each module/class would have to change to use some interface that knows how to extract a type from the string, possibly ignoring comments. More important, I think the fact that this approach only allows trailing comments on *some* lines is a fatal flaw. How would we document which lines allow trailing comments and which do not? I'd prefer a solution that is easy to explain.

What I'm proposing is simple:  if you have a `#` (0x23 to be clear) in your config file, everything after and including the `#` will be treated as a comment *unless* it is immediately preceded by a `\` (0x5C). I understand what you are saying generally about escaping-escapes, but we're not trying to build a general parser here so I don't think it's needed. If you want to include an actual `#` in your key/value/line, then type it as `\#`. If you want a key/value/line that ends in `\` and you want to then add a trailing comment, just add a space - everyone will prefer the space and we won't think you are escaping in that case.

As for users having to modify their existing configs - it is extremely unlikely anyone has a *meaningful* `#` in their config file currently. I think of our field "types", only password and file-paths could even possibly include this char, but it's highly unlikely anyone does actually have them. That said, I'm suggesting we emit a warning to the log IF we stripped any trailing comments using the approach above - the warning message would alert the operator that the treatment of `.... #...` in config files has changed and the user should add escapes for any `#` that they intend to keep.

@MarkusTeufelberger I agree that a standard format moving forward makes sense (TOML or whatever). This proposed change was intended to be a stop-gap measure to help prevent the unpleasantness of ignored config lines when the include trailing comments. Such a change does not preclude or disincentivize moving to a more maintainable format.

**Comment by scottschurr** [comment]
@mellery451, thanks for the thorough explanation.  You have good reasons for the choice you made.  I withdraw my suggestion.  Charge ahead.
