### ISSUE TITLE
rippled to provide native gRPC support

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3127]
This is to track the progress of gRPC support for RippleD

**Comment by rayeaster** [comment]
> This is to track the progress of gRPC support for RippleD

is this already on rippled roadmap or planned sprint in near future? Thanks

**Comment by MarkusTeufelberger** [comment]
Could we please have a bit more documentation + discussion about this feature before it is implemented? Seems like this is some weird requirement(?) from xSpring's connector library? How about adding a REST API to `rippled` as well? XMLRPC? OpenAPI? FIX? OpenMAMA? These all would be nice to have at some point, but maybe would be better implemented by a middleware layer...

**Comment by carlhua** [comment]
> 
> 
> Could we please have a bit more documentation + discussion about this feature before it is implemented? Seems like this is some weird requirement(?) from xSpring's connector library? How about adding a REST API to `rippled` as well? XMLRPC? OpenAPI? FIX? OpenMAMA? These all would be nice to have at some point, but maybe would be better implemented by a middleware layer...
> 
> Edit:
> Especially if the goal is to add the protos + rpc calls from https://github.com/xpring-eng/xpring-common-protocol-buffers which seem to encode everything as string (sometimes even "in hexadecimal"!) instead of using typing and are as minimal as it gets. Through the usage of strings and not implementing all available fields alone they kinda messed up their goal of backwards compatibility from the get-go, since every field added to a "Transaction" (https://github.com/xpring-eng/xpring-common-protocol-buffers/blob/master/proto/transaction.proto) for example now will either be a breaking change or an optional extension. I'd strongly advise against implementing this API into rippled in that form and would STRONGLY urge you to get someone on board who is experienced with gRPC and API design first.

We will be providing documentation shortly. In short, we are creating native gRPC support within RippleD in addition to the existing websockets and json support. This service will run aside the other API services. gRPC uses protobuf. protobuf is not encoded in string - it is in binary over the wire and is highly optimized and performant. The plan is to provide full capability for the APIs we are implementing. Although initially we would only support a subset of the APIs but one can expect these to be full capability of APIs provided by other interfaces. In addition to gRPC we also plan to provide API versioning so that the existing sets of APIs will continue to be supported.

**Comment by MarkusTeufelberger** [comment]
Alright, so why do your protobuf files in https://github.com/xpring-eng/xpring-common-protocol-buffers then set the type a lot of fields as "string" instead of "bytes" for example?

Sorry, but I am a bit skeptical when looking at the quality of the protos in that repository and the fact that you misspell the name of the software you want to change about this endeavour. I general I think adding gRPC is a good idea, however I would expect to have full support for the existing JSON-RPC calls and proper(!) typing for the individual fields. I wouldn't mind some calls being implemented first and then gradually expanding the API, but I would NOT like to have existing calls changing (e.g. fields being added, changed or removed) unless you also add a version parameter to every call.

Check out the difference between https://github.com/xpring-eng/xpring-common-protocol-buffers/blob/master/proto/account_info.proto and https://xrpl.org/account_info.html for example. If your explicit goal is to maintain backwards compatibility ("Because this library is widely consumed, it must remain backwards compatible. In most cases, Xpring will be cautious to add new functionality as it increases the maintenance burden of backwards compatibility." - https://github.com/xpring-eng/xpring-common-protocol-buffers/blob/master/CONTRIBUTING.md), it already seems as if a proper 1:1 implementation of that relatively simple API call is no longer possible with the xspring framework if you want to actually want to keep your promise and stay backwards compatible.

By the way: All this is NOT necessary to write a gRPC interface to rippled - you can easily write a middleware in go for example that speaks JSON-RPC with rippled and gRPC with your framework. I'd expect to see that approach first, before adding a lot of complexity here in places that already are a bit in flux (e.g. APIs currently are not versioned, so it is already quite hard to deprecate or change them without impacting users).

**Comment by carlhua** [comment]
@MarkusTeufelberger  Thanks for your candid feedback.

Some clarification here:
1. The account_info API you referenced is NOT final. It will be updated to provide full capability. The proto file will also go through review. This is also not the final proto rippled will use. This proto is created to be used between the SDK and a middleware which is a layer on top of rippled to service gRPC requests. Although they are similar, we can expect these proto files to change. So please bear with me for now.
2. gRPC support will not have any impact to existing APIs serviced by Websockets and JSON-RPC. So existing calls will NOT change. API versioning is also something currently in the works. With API versioning, rippled will be able to provide backward/forward compatibility without worrying about breaking APIs.
3. With native gRPC support, it is our goal to provide full capability APIs that map 1:1 to websockets and JSON-RPC APIs functionally. Initially this will be a subset of the mapping but as times goes on, the goal is to ramp up and provide 1:1 mapping in the future. Again, since there will be no impact to Websockets and JSON-RPC, I do not see an issue with only providing a subset of the full APIs initially.
keefertaylor
I understand your skepticism since little documentation has been provided on how rippled will provide gRPC and I kindly ask you to patiently wait for the documentation. I created this issue to track work and as part of this process, we will be providing design artifacts. You will get another round of opportunity to provide comments.

**Comment by yxxyun** [comment]
since grpc use protobuf to do the serialization,  do we still need 
 https://xrpl.org/serialization.html this to serialization transaction?

**Comment by MarkusTeufelberger** [comment]
Depends on the implementation - if you are signing transactions offline, you'll definitely also want to serialize a transaction yourself. This is about adding an API, not the way transactions are actually handled/serialized in the protocol itself (which rippled implements and this documentation describes).

**Comment by keefertaylor** [comment]
Chiming in here as well: 

Like Carl noted, we're still at the prototype phase on a lot of these objects. You're looking at what is an MVP that proves out the technology stack as useful, rather than a fully final design. 

In terms of your gripes about protocol buffers:  
- I admit the `Transaction` / `SignedTransaction` is a bit of an odd pattern that we should think about before committing to. We already have a wire serialization format, there's probably no need to invent another one. 
- Likewise, I'm not thrilled at the way we represent amounts of XRP / Issued currencies. We're looking into what changes we can make here. 
- On `strings` vs `bytes`: 
These both [encode over the wire](https://developers.google.com/protocol-buffers/docs/encoding) the same way. `strings` are used because that's what the JavaScript code we depend on tends to use to pass data around. Your gripe is just that developers could stuff non-hex chars into a string field? 
- On the breaking protocol buffer / service changes: 
Not sure I understand why you think adding additional fields to transactions is an issue. Protocol buffers are inherently backwards compatible (gRPC definitions are not though). 

It seems sane that if a field in `AccountInfo` isn't implemented yet that the API could default to the default value. When that field gets added to `AccountInfo` then the field will default to the default value anyway.  Obviously, doing this *frequently* becomes a bit of an issue to keep track of versions, but it's not impossible to add a field after you've released a protocol buffer into the wild. (NOTE: I'm *not* advocating for this approach - simply looking at the plausibility of it. As noted, we plan on expanding out to have the full API when this gets plumbed into gRPC). I'm curious what you think will force us into using extensions here.   

I'll also note there's some dance to getting the rippled nodes and Xpring SDK to update in lockstep since there's no centrally managed API, but I imagine that most developers who are working with Xpring SDK are also running their own nodes.

- In regards to middleware: We're running (hosted) middleware now as a proof of concept.

**Comment by keefertaylor** [comment]
> since grpc use protobuf to do the serialization, do we still need
> https://xrpl.org/serialization.html this to serialization transaction?

gRPC will figure out how to ferry the transaction data to the node after being signed and serialized.

**Comment by nbougalis** [comment]
@MarkusTeufelberger, thanks for your feedback; as always, you keep us on our toes.

I think that consideration about typing (e.g. `string` vs. `bytes`) are important vis-à-vis having a clean and "error-proof" API, and we will have an opportunity to review and make adjustments as we go. This is still early, and we're taking this opportunity to do a proof of concept.

Nothing has been set in stone yet. We haven't even settled on whether this layer really belongs in `rippled` proper, or in a kind of ancillary process that's outside the core executable; we are investigating options at this time.

Please keep a watch on the progress, and feel free to comment. We are open to constructive criticism and certainly appreciate your thoughtful contributions.

**Comment by yxxyun** [comment]
the grpc Prototype branch
https://github.com/cjcobb23/rippled/tree/grpcPrototype

**Comment by MarkusTeufelberger** [comment]
Ouch, just as I worried...

https://github.com/cjcobb23/rippled/blob/grpcPrototype/proto/rpc/v1/amount.proto "FiatAmount"?! What kind of name is that? An issuance/IOU on the ledger doesn't have to be a fiat currency at all. The RippleState one is even more "interesting" with low and high nodes as int64(?!?).

At least a lot of fields now are integers and bytes, though apparently account addresses and keys are encoded as string for some reason.

I would recommend writing and feedbacking the proto files first and then implementing the RPC calls behind them - otherwise there will be a lot of refactoring and rewriting. OTOH this seems to be done by an external/aquihired team(?), so maybe this is their first task to get more deeply into the code base?

**Comment by cjcobb23** [comment]
low and high node are int64 in the current api: https://xrpl.org/ripplestate.html
account addresses are also strings in the current api: https://xrpl.org/accountroot.html
On the above page, you can see that account addresses are returned in the form of a base58 string, as opposed to hex bytes. Therefore, the acccount addresses are actually strings, as opposed to bytes. They are meant to be human readable. The same goes for other data that is returned in base58, as opposed to hex.

It's fine if you don't like the way some things are being named or implemented. There will be a rigorous review process where we address things like that. The proto files will be part of the code review. Changing aspects of the protobuf messages, like the name of fields, or even their types, will not cause huge changes to the source code. Furthermore, the protobuf files mirror the existing API very closely, so changes to the protobuf files would be small things, like changing types or names, or adding a few more fields, as opposed to some total rewrite.

**Comment by yxxyun** [comment]
I also think FiatAmount isn't a good name,  currently both bitstamp and gatehub issue BTC on XRPL,  when we send BTC payments, call it fiatamount is odd.

**Comment by cjcobb23** [comment]
What name would you suggest then?

**Comment by yxxyun** [comment]
Something like XRP to Native , IOU to Credit.

**Comment by intelliot** [comment]
@cjcobb23 I think it would be fine to use one of the current names, like IOU or issued currency. For Amount, consider just calling it an amount.

https://xrpl.org/issued-currencies-overview.html

**Comment by sublimator** [comment]
asset

protobuf files should probably be generated

actually @nbougalis was talking a while ago about having a single source of
truth for the fields/enums/etc and then a command line tool to generate the
C++ defs and whatever other languages. Maintaining them by hand is a real
pain.

lownode/highnode are unsigned 64 bit ints

**Comment by sublimator** [comment]
didn’t see much context here and the full conversation - but still get
notifications for rippled issues - apologies if not making sense

**Comment by cjcobb23** [comment]
@sublimator you're saying the *. proto files themselves should be generated? From what? Why can't the proto files themselves be the single source of truth?

**Comment by cjcobb23** [comment]
And if the proto files themselves are not actually part of the repo, client libraries don't have access to the interface. Client libraries would have to generate the proto files as well

**Comment by sublimator** [comment]
If that makes sense. Must admit I don’t know what you guys are doing, just
from scanning comments in this thread seemed like creating hand crafted
protos of ripple objects.  e.g. comments re: RippleState HighNode/LowNode

**Comment by sublimator** [comment]
having them generated wouldn’t necessarily mean not having them committed
to some repo

**Comment by sublimator** [comment]
or partially generated for that matter ...

**Comment by cjcobb23** [comment]
Oh I see. Yeah if the proto files are still committed to the repo, I think generating them is not a bad idea. I think we could also use the proto files as the interface definition, and generate code from the proto files. Either way, I do see the benefit of a single source of truth

**Comment by sublimator** [comment]
https://github.com/ripple/rippled/pull/1972#issuecomment-518453976

for reference ^

Sure @nbougalis may have some ideas on where that all fits in with ya proto
project
