### ISSUE TITLE
Storage usage out of control

### ISSUE THREAD

**Issue by yinjun1991** [ripple/rippled#3169]
I run a xrp regular node (not validator, version 1.3.1) in my private net on aws.

My server hardware:
```
4core
8GB RAM
100GB SSD
```

My conf:
```
[server]
port_rpc_admin_local
port_peer
port_ws_admin_local
port_ws_public
#ssl_key = /etc/ssl/private/server.key
#ssl_cert = /etc/ssl/certs/server.crt

[port_rpc_admin_local]
port = 8897
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http

[port_peer]
port = 51235
;ip = 0.0.0.0
# alternatively, to accept connections on IPv4 + IPv6, use:
ip = ::
protocol = peer

[port_ws_admin_local]
port = 8898
ip = 0.0.0.0
admin = 0.0.0.0
protocol = ws

[port_ws_public]
port = 8899
ip = 0.0.0.0
admin = 0.0.0.0
protocol = ws


[crawl]
0

[node_size]
small

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=1000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=75000
advisory_delete=1

[database_path]
/var/lib/rippled/db

[ledger_history]
75000

[fetch_depth]
51693980

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[validator_list_sites]
https://vl.ripple.com

[validator_list_keys]
ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734

[ips_fixed]
r.ripple.com 51235
zaphod.alloy.ee 51235

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
0
```

My OS is ubuntu, so i use crontab, My crontab task:
```
5 1 * * * /usr/local/bin/rippled --conf /etc/opt/ripple/rippled.cfg can_delete now
```

Now the storage usage is 100%, and rippled is out of sync.  I found no `Not deleting` message and no `SHAMapStore::WRN` in `/var/log/rippled/debug.log`

According to the doc, 75000 will be 24GB in RocksDB.
<img width="667" alt="xrp" src="https://user-images.githubusercontent.com/4370991/69911373-930b7a00-1455-11ea-8645-e8d2c2dacfe5.png">

I wonder why, How should i do to resolve this problem?

**Comment by MarkusTeufelberger** [comment]
The ledger is currently being spammed with constantly ~3 times more transactions than the previous all time high.

See the next paragraph on the page you screenshotted above:

> These numbers are estimates. They depend on several factors, most importantly the volume of transactions in the network. As transaction volume increases, each ledger version stores more unique data. You should provision extra storage capacity to prepare for future growth.

**Comment by yin-june** [comment]
I thought you should update the doc. Otherwise this question will be very tricky to a novice.

I change `online_delete` to 30000, delete all data, disable `advisory_delete`, restart rippled.

But now, the complete_ledgers is `51730292-51762673`, more than 30000. The storage usage is 50GB.

Why rippled didn't clean the redundant old ledgers to keep ledgers to 30000 ?

**Comment by yxxyun** [comment]
https://xrpl.org/online-deletion.html

> The server may store up to just over twice the configured number of ledger versions if online deletion is set to run automatically. (Each time it runs, it reduces the number of stored ledger versions to approximately the configured number.)

> If online deletion is delayed because the server is busy, ledger versions can continue to accumulate. When functioning normally, online deletion begins when the server has twice the configured number of ledger versions, but it may not complete until after several more ledger versions have accumulated.

**Comment by nbougalis** [comment]
There's not enough information there for us to help. Like how much storage is being used and what the _actual_ message the server returned in response to the attempted execution of advisory deletion. Please note that deletion will not delete when it's out of sync or doesn't have a recent enough ledger, so this message would make sense if you server was, as you report, out of sync.

A few more comments.

First, the **`fetch_depth`** you've configured seems incorrect. The description of that setting from the default config file is:

```
#   The number of past ledgers to serve to other peers that request historical
#   ledger data (or "full" for no limit).
```

You're literally offering to server 51,693,980 ledgers. It's theoretically possible that you intended to do this but it is exceedingly unlikely and something that your server will **never** be able to do given the online-delete configuration you have.

Unless it's your intention to operate a full history server (which you aren't, given other configuration settings you have), and considering your **`node_size`**, your database configuration my _recommendation_ would be to set **`fetch_depth`** to either **`none`** or to **`256`**.

**Comment by yin-june** [comment]
> There's not enough information there for us to help. Like what the _actual_ message the server returned in response to the attempted execution of advisory deletion and what is consuming all the disk space.
> 
> In reference to the message you saw, please note that deletion will not delete when it's out of sync or doesn't have a recent enough ledger, so this message would make sense if you server was, as you report, out of sync.
> 
> A few more comments:
> 
> First, the **`fetch_depth`** you've configured seems problematic to me. The description of that setting from the default config file is:
> 
> ```
> #   The number of past ledgers to serve to other peers that request historical
> #   ledger data (or "full" for no limit).
> ```
> 
> You're literally offering to server 51,693,980 ledgers. It's possible that you intended to do this but it is exceedingly unlikely. It's also something that your server will **never** be able to do given the online-delete configuration you have.
> 
> Unless it's your intention to operate a full history server (which you aren't, given other configuration settings you have), and considering your **`node_size`** and database configuration, my _recommendation_ would be to set **`fetch_depth`** to either **`none`** or to **`256`**.

Thank you, I config the `fetch_depth`, because if rippled down, when i delete all data, and restart it. I want to resync from the ledger version `51693980`. Because the first transaction in my account is from this ledger version, and i have to get my full history transaction.

Obviously, i misunderstand the meaning of fetch_depth.

For now, i have no idea how can i get my goal. I wish:
1. Keep rippled running normal.
2. When i restart rippled, i want rippled sync from a specific height, so i can get my full transaction history. When the ledger is too old, rippled could delete the old ledger, and keep sync the latest ledger. run like a flow window, the window size is `online_delete `.

**Comment by yin-june** [comment]
> https://xrpl.org/online-deletion.html
> 
> > The server may store up to just over twice the configured number of ledger versions if online deletion is set to run automatically. (Each time it runs, it reduces the number of stored ledger versions to approximately the configured number.)
> 
> > If online deletion is delayed because the server is busy, ledger versions can continue to accumulate. When functioning normally, online deletion begins when the server has twice the configured number of ledger versions, but it may not complete until after several more ledger versions have accumulated.

Sorry, I'm very confused about this setting. In my opinion, the first most thing is to keep rippled running consistently.

The field `online_delete` means the storage is limit, rippled should release the storage and receive the coming blocks, is this right ?

I think the delete action has higher priority than other tasks, otherwise rippled will down because no storage. What's the meaning of `busy` if rippled running to down ?

**Comment by MarkusTeufelberger** [comment]
You will need (far) more than 100 GB disk space for these criteria (and your 8 GB RAM are also very low btw). What you seem to want is every ledger after a certain one. This is very close to a full history config (just that your initial ledger is not 32570 but 51 million something). You don't need online_delete for this. Instead you need to tell your node to store full history and set the `earliest_seq` config to `51693980`.

Your server then will on startup sync with the network and download all data it doesn't already have that makes up the ledgers from whenever you started back to ledger `51693980`.

**Comment by MarkusTeufelberger** [comment]
Your config would look something like this:

```
[node_db]
.
.
.
earliest_seq=51693980

[ledger_history]
full

# (no fetch_depth setting, or none or 256, depending on what your node can handle)
```

Oh, and please don't bind admin ports to 0.0.0.0 unless you're sure you know what you're doing and why...

**Comment by yin-june** [comment]
> Your config would look something like this:
> 
> ```
> [node_db]
> .
> .
> .
> earliest_seq=51693980
> 
> [ledger_history]
> full
> 
> # (no fetch_depth setting, or none or 256, depending on what your node can handle)
> ```
> 
> Oh, and please don't bind admin ports to 0.0.0.0 unless you're sure you know what you're doing and why...

Thank you. 
I mean, my service crawler the xrp chain, record my transaction history to db. 
So if my rippled down, my service will stop at the last ledger, assume the ledger version is 51700000.
When i restart rippled, i want rippled sync from the height 51700000, so my service will resume to record the later transactions.
I don't need full history, but need continuous history.

**Comment by MarkusTeufelberger** [comment]
You can only sync backwards in time by going from block to block. You could set your earliest_seq to 51700000 to sync back to that point later on, but your server can't know what's in ledger 51700001 (or how to find it) until it has ledger 51700002 and so on. There are some shortcuts built into the ledger to be able to know older ledger versions faster, but I'm not sure if rippled actually uses them (the skip lists).

In general rippled is typically more built towards serving complete data to anyone rather than being optimized for storing only/mostly data for a single account (or a small set of them).

**Comment by yin-june** [comment]
> You can only sync backwards in time by going from block to block. You could set your earliest_seq to 51700000 to sync back to that point later on, but your server can't know what's in ledger 51700001 (or how to find it) until it has ledger 51700002 and so on. There are some shortcuts built into the ledger to be able to know older ledger versions faster, but I'm not sure if rippled actually uses them (the skip lists).
> 
> In general rippled is typically more built towards serving complete data to anyone rather than being optimized for storing only/mostly data for a single account (or a small set of them).

Yeah, i know the block chain is to keep data of all account. But i just wanna crawler the chain and record my history continuously.
The scene is common, like a payment service, or an exchange.
I think rippled could do more and better on syncing, from low(min) to high(max), but no high(max) to low(low).
Imagine, rippled is down, somehow 4 days later i'm aware of it. My node has only 100GB storage(3 days capacity). I will never get my history in the first day.

**Comment by yxxyun** [comment]
Maybe History Shard can work for your case. You can store the History Shard including your accounts transaction.

**Comment by nbougalis** [comment]
I'm trying to understand what you want to do: your primary goal is to make sure that your server has ledgers starting from ledger **`51693980`** because that's the earliest ledger that contains data that is useful for you?

Unfortunately, there's no particularly easy way to do that, with the default `rippled`. 

I agree with you that being able to configure such "advanced" modes would be cool, but unfortunately, that's not always possible; every configurable option carries a cost (in code, in complexity for admins and complexity for users).

**Comment by intelliot** [comment]
@yin-june Is your primary constraint the 100GB of storage -- Would increasing your storage capacity resolve your issue? I suggest an SSD of at least 1TB; looks like they can be obtained for around $100-200.

**Comment by yin-june** [comment]
I set the online_delete to 25000, the storage usage is at average 50%, looks like worked.

**Comment by nbougalis** [comment]
Great. If things look good and you don't have any further questions, please close this issue.
