### ISSUE TITLE
Have all the transactions in the "validated" ledger been "validated"?

### ISSUE THREAD

**Issue by GuiltyMorishita** [ripple/rippled#3187]
I requested a validated ledger and then I immediately requested the transaction included in the response again.
In that case, "validated: false" ones may be returned.
Can I consider all transactions in validated ledger to be validated?

Below is a sample request.

```
## ledger
curl -X "POST" "http://localhost:5005/" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "id": "1",
  "method": "ledger",
  "jsonrpc": "2.0",
  "params": [
    {
      "expand": true,
      "transactions": true,
      "ledger_index": "validated"
    }
  ]
}'
```

```
## tx
curl -X "POST" "http://localhost:5005/" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "id": "1",
  "method": "tx",
  "jsonrpc": "2.0",
  "params": [
    {
      "transaction": "Response value of previous request",
    }
  ]
}'
```

**Comment by intelliot** [comment]
@GuiltyMorishita Due to the asynchronous nature of these requests, there's a race condition where the "ledger" method may return data that is not yet indexed for use by the "tx" method. You can consider transactions in a validated ledger to be validated, but do not consider transaction results or transaction metadata to be validated (and immutably finalized) if you do not see `"validated": true` in the response for your "tx" request. When a transaction is validated, that is when its result and metadata are finalized.

For example, a transaction that tentatively succeeds may later fail (perhaps with a `tec` code) when it appears in a validated ledger. Or a transaction that failed could later succeed. Or a transaction that succeeded could later succeed with a different result (for example, if using a payment path, by getting a different exchange rate or delivering a different amount).

If you want to be sure that the result and metadata are final and won't change, you can only rely on validated data. Fortunately, this only takes 3-5 seconds, so I recommend waiting for a brief period and then retrying the request.

**Comment by GuiltyMorishita** [comment]
Thank you!
