### ISSUE TITLE
manifest command CLI format: publicMalformed error (Version: 1.5.0-rc1)

### ISSUE THREAD

**Issue by mDuo13** [ripple/rippled#3317]
The `manifest` command introduced in #3197 doesn't seem to work when I use it on the commandline.

## Issue Description
I successfully used the `manifest` command in both WebSocket and JSON-RPC to get the manifest info for alloy.ee using my server, for example JSON-RPC:

```json
{
    "method":"manifest",
    "params": [{"public_key":"nHUFE9prPXPrHcG3SkwP1UzAQbSphqyQkQK9ATXLZsfkezhhda3p"}]
}
```

However, the CLI syntax consistently gives me an error message.

## Steps to Reproduce

```
$ ./rippled manifest nHUFE9prPXPrHcG3SkwP1UzAQbSphqyQkQK9ATXLZsfkezhhda3p 
```

(Putting the key in quotes or not makes no difference.)

## Expected Result
The response should match the JSON-RPC response, like this:

```json
{
  "result": {
    "details": {
      "domain": "",
      "ephemeral_key": "n9J67zk4B7GpbQV5jRQntbgdKf7TW6894QuG7qq1rE5gvjCu6snA",
      "master_key": "nHUFE9prPXPrHcG3SkwP1UzAQbSphqyQkQK9ATXLZsfkezhhda3p",
      "seq": 1
    },
    "manifest": "JAAAAAFxIe3AkJgOyqs3y+UuiAI27Ff3Mrfbt8e7mjdo06bnGEp5XnMhAhRmvCZmWZXlwShVE9qXs2AVCvhVuA/WGYkTX/vVGBGwdkYwRAIgGnYpIGufURojN2cTXakAM7Vwa0GR7o3osdVlZShroXQCIH9R/Lx1v9rdb4YY2n5nrxdnhSSof3U6V/wIHJmeao5ucBJA9D1iAMo7YFCpb245N3Czc0L1R2Xac0YwQ6XdGT+cZ7yw2n8JbdC3hH8Xu9OUqc867Ee6JmlXtyDHzBdY/hdJCQ==",
    "requested": "nHUFE9prPXPrHcG3SkwP1UzAQbSphqyQkQK9ATXLZsfkezhhda3p",
    "status": "success"
  }
}
```

## Actual Result

A `publicMalformed` error such as this:

```json
{
   "error" : "publicMalformed",
   "error_code" : 62,
   "error_message" : "Public key is malformed.",
   "rpc" : {
      "method" : "manifest",
      "params" : [ "nHUFE9prPXPrHcG3SkwP1UzAQbSphqyQkQK9ATXLZsfkezhhda3p" ]
   },
   "status" : "error"
}
```

## Environment
Arch Linux x86_64, self-compiled rippled v1.5.0-rc1
Synced to mainnet.

**Comment by nbougalis** [comment]
Looking at the code, we land at [`ripple::RPCParser::parseManifest`](https://github.com/ripple/rippled/blob/1.5.0/src/ripple/net/impl/RPCCall.cpp#L221-L237).

The function calls [`ripple::RPCParser::validPublicKey`](https://github.com/ripple/rippled/blob/1.5.0/src/ripple/net/impl/RPCCall.cpp#L148-L161) and a closer look at that function reveals it attempts to parse its input as base58 and if that fails, it falls back to hex.

The input you provided certain is base58, so it should work. But it doesn't:

        if (parseBase58<PublicKey> (TokenType::AccountPublic, strPk))
            return true;

The problem is that it only attempts to account `TokenType::AccountPublic` encoded keys, and the key you provided is `TokenType::NodePublic` instead.

This function is called from several places so it can't just be arbitrarily changed. My suggestion would to add a new parameter to the `validPublicKey` that accepts the type of public key being decoded as a command line argument, and passing the correct type.

**Comment by nbougalis** [comment]
![image](https://user-images.githubusercontent.com/5085415/104444396-94f6a680-554c-11eb-86bf-be8923f37d05.png)
