### ISSUE TITLE
EnableAmendment timer starts at 77.78% (Version: [rippled 1.5.0])

### ISSUE THREAD

**Issue by gnurag** [ripple/rippled#3396]
## Issue Description
I may be reading this incorrectly - but I think the 14 day timer to enable an amendment starts at `77.78%` (28 Ayes out of 36 as of today). 28 Ayes of 36 is only `77.78%` agreement. [Amendment process](https://xrpl.org/amendments.html#amendment-process) doc says this must be `80%` or above.

Observed this behavior with [`RequireFullyCanonicalSig`](https://xrpl.org/known-amendments.html#requirefullycanonicalsig) amendment which is hovering around 27 Ayes at the moment. Once it achieved 28 Ayes (=`77.78%` agreement), the validator inserted an [EnableAmendment transaction](https://xrpcharts.ripple.com/#/transactions/0F699B1AC8AF0B112E7AE855ACAD14F3009245CB5D4582EFCE720CB86132C5E6) and the 14 day timer started.

![fullycanonicalsig-vote](https://user-images.githubusercontent.com/13650/81534663-0ced4b00-9386-11ea-9b1d-126d2339578e.png)

## Steps to Reproduce
Run:
```
# /opt/ripple/bin/rippled feature
```
on the validator when an amendment has 28 Ayes out of 36. 

## Expected Result
1. [EnableAmendment transaction](https://xrpcharts.ripple.com/#/transactions/0F699B1AC8AF0B112E7AE855ACAD14F3009245CB5D4582EFCE720CB86132C5E6) is not inserted into the ledger.
2. `majority` property is not set.

## Actual Result
1. [EnableAmendment transaction](https://xrpcharts.ripple.com/#/transactions/0F699B1AC8AF0B112E7AE855ACAD14F3009245CB5D4582EFCE720CB86132C5E6) is inserted into the ledger.
2. `majority` property is set (see screenshot above).

## Environment
rippled-1.5.0 

## Supporting Files

![fullycanonicalsig-votes](https://user-images.githubusercontent.com/13650/81535679-dc0e1580-9387-11ea-9f94-f3da8e034358.png)

**Comment by nbougalis** [comment]
Thanks for opening an issue. A couple of people had already reached out to me about the DeletableAccounts amendment, wondering how come it reached majority, since 28 validators seem to support it but (a) the consensus quorum is presently 29 and (b) 28/36 is strictly less than 80%, which is the amendment activation threshold, so I already had a chance to triage this..

The answer boils down to two things:

First, for historical and largely obsolete reasons, the calculation for the majority is done in base 256, with the quorum threshold set to `(V * 204)/256` where `V` is the total number of trusted validations. There are currently 36 validators on Ripple's recommended UNL, so I am assuming a server running with a UNL with a size of 36 for this example, but similar calculations apply for other sizes:

So the code calculates `(36 * 204) / 256`. [Ref](https://github.com/ripple/rippled/blob/1.5.0/src/ripple/app/misc/impl/AmendmentTable.cpp#L477-L482):

```
vote->mThreshold = std::max(1,
    (vote->mTrustedValidations * majorityFraction_) / 256);

JLOG (j_.debug()) <<
    "Received " << vote->mTrustedValidations <<
    " trusted validations, threshold is: " << vote->mThreshold;
```

Now, if you plug that into a calculator you'll see it works out to 28.6875. So what's wrong?

The code is using integer arithmetic, which "truncates toward zero’’. Basically, you can think of it as "rounding down to the nearest integer" and what is the nearest integer that is strictly smaller? It's **28**. For a little deeper dive into this check out [this excellent StackOverflow answer](https://stackoverflow.com/questions/3602827/what-is-the-behavior-of-integer-division).

The second, problem is that the code checks whether an amendment has achieved the required quorum by using **greater than or equal to** instead of **strictly greater than**. [Ref](https://github.com/ripple/rippled/blob/1.5.0/src/ripple/app/misc/impl/AmendmentTable.cpp#L496-L497):

```
bool const hasValMajority =
    (vote->votes (entry.first) >= vote->mThreshold);
```

While the behavior of the code is well-defined in terms of C/C++, it's not ideal from a human perspective and certainly complicates the understanding of quorum when it comes to amendments.

I believe that this issue needs to be addressed in a future release of `rippled`, preferably with the **1.6.0** release. Ironically, the fix will require an amendment. :sweat_smile:
