### ISSUE TITLE
Unexpected current sequence(Version: [1.5.0])

### ISSUE THREAD

**Issue by shota-hizawa** [ripple/rippled#3401]
## Issue Description
My xrp account on testnet has set wrong sequence.
Transactions from the account in the picture below is less than ten, however, its current sequence is 7,114,878(maybe related to ledger index?).
![image](https://user-images.githubusercontent.com/42070729/81927661-fc0b3680-961e-11ea-837d-fec3acc85026.png)

## Steps to Reproduce
I guess accounts created after few days ago is facing this problem.

## Expected Result
Account sequence should be set appropriate value.

## Actual Result
Account sequence has set unexpeceted value.

## Environment
My wallet node is running rippled v 1.5.0 on amazon linux2. 

## Supporting Files
I found the same issue is going on the acccounts below.
```
rQr34nTtPBhXPhn2onx7TMc7AZKjZi86YU
rKrXXbGjsUuKUhAkm4dQxd7UN1iJyTvxU6
r4BmT8s9Yb3X3cJMgFZQghecSXcmA5LvyL
```

**Comment by carlhua** [comment]
@shota-hizawa this is by design since we now have activated  DeletableAccounts via Amendment: "With this amendment, new accounts start with their Sequence numbers equal to the Sequence number matching the index of the ledger in which the account is created. " For more information, see here: https://xrpl.org/known-amendments.html#deletableaccounts

**Comment by intelliot** [comment]
For details about getting ready for Deletable Accounts, see the blog post: https://xrpl.org/blog/2020/get-ready-for-deletable-accounts.html

**Comment by shota-hizawa** [comment]
@carlhua @intelliot 
Thank you for quick response! I close this issue.
