### ISSUE TITLE
Reporting Mode

### ISSUE THREAD

**Issue by cjcobb23** [ripple/rippled#3414]
## Problem

Rippled stability and scalability are limited because it supports multiple distinct workloads in the same process: transaction processing and reporting. Namely, individual rippled peers tend to lose synchronization with the consensus network when subjected to heavy reporting traffic or deleting large amounts of historical data. Optimizing for one workload comes at the expense of the other when working within a single process. Instead, dividing distinct tasks among processes allows optimizations to be made for each without sacrificing either.

To facilitate this, a separate mode for rippled will be created, called Reporting Mode. Reporting mode will not be connected to the peer to peer network, and subsequently will not process transactions. The main function of a node running in Reporting Mode will be to handle RPC requests for validated data. The reporting node will get this data via a continuous ETL mechanism.

The mode that rippled runs in today, where the node is connected to the peer to peer network and processes transactions, will be called transaction processing mode.

## Motivation
The motivation for this project is two fold. Running a reporting node allows one to offset load from the transaction processing node imposed by RPC traffic (as well as load imposed by storing validated data), so that the transaction processing node has more resources to process transactions and keep up with the network. In the future, we can also create a leaner transaction processing mode, that persists no or very little validated data.

The second motivation is to facilitate scalable reporting systems, via using network accessible databases that are used by a cluster of reporting nodes.

### ETL
The ETL will be performed via RPC. The reporting node will subscribe to the `ledgers` stream of a transaction processing node. Whenever a message is received on the stream, reporting mode will then call the `ledger` RPC to get the data for the newly validated ledger. Reporting mode will use this data to update it's copy of the ledger. The `ledger` RPC will be tweaked to allow for an efficient and simple ETL.

### Databases
As part of this project, we will be implementing functionality that allows rippled to use network accessible databases instead of embedded databases. Postgres can be used in place of SQLite. Cassandra can be used in place of NuDB or RocksDB. The use of these databases will be optional; reporting mode will be able to use the old databases as well.

The idea behind using network accessible databases is to be able to more easily store large amounts of data. Cloud hosted solutions can even be used, which automate infrastructure management, such as scaling and replication. Furthermore, network accessible databases allow multiple reporting nodes to use the same databases. In this setup, one can run a cluster of reporting nodes that all read from the same network accessible databases; only one node would need to write to the database. This allows for quick bring up of additional reporting nodes.

### Proxy
The reporting node can serve as a proxy to the transaction processing node, such that RPC requests that require access to the peer to peer network (`submit` for example) will be forwarded to the transaction processing node. Reporting nodes can also forward RPCs that request not yet validated data (for example, `ledger` with `ledger_index` set to `current`) to the transaction processing node. This proxying behavior will be configurable, such that reporting nodes can refuse to forward some or all RPCs to the transaction processing node.

**Comment by cjcobb23** [comment]
@MarkusTeufelberger what do you think of this? We created this issue to give the community a heads up about this upcoming feature, and to give the community an opportunity to provide feedback.

**Comment by MarkusTeufelberger** [comment]
I thought that was what middleware like xumm or xpring or https://github.com/ripple/rippled-historical-database was for? Why put all this into `rippled` itself, especially if it isn't even going to connect to other servers or process transactions?

Personally I think that running several instances of `rippled` in e.g. Kubernetes with proper load balancing and auto-scaling enabled should be enough to be able to handle even extreme cases of RPC traffic, but there's no public data that I know of about the actual load on servers. Having a single-writer, multiple readers database shared between instances sounds like a good idea though, I'd also like to maybe see a shared cache (Redis or Memcached) instead of a full Cassandra cluster for K/V data.

I proposed something to get the data that has changed between 2 ledgers efficiently about 5 years back (#1343), so it sounds a bit surprising that this is now suddenly getting traction for not only being implemented as the producer of such data but also at the same time to have rippled run in a consumer mode. If you want to actually run a caching proxy, I'd rather recommend writing a filter for envoy (here's an example project: https://github.com/envoyproxy/envoy-filter-example) instead of modifying `rippled`. That way you could choose exactly which RPC calls to cache and what to forward and would get a lot of other benefits on top - without having to rewrite `rippled`. It could also deal with gRPC.

I'm somewhat worried that someone attaching such a reporting node to a transaction processing node will just cause the same kind of load there (constant RPC traffic for ledger data) and the really expensive RPC calls (run https://xrpl.org/ledger.html with `full: true` on an admin port and measure how long it takes and what kind of IO this causes) would still overwhelm any node in any configuration, old or new.

Personally for scaling access to historic data I'd rather see something that's not `rippled`, but that can be fed shard databases and maybe expand them into something indexable, so only data from the most recent ~2 days has to be queried from `rippled` instances. Having a way to get all data that has changed since a certain ledger would definitely help, though I'm not so sure if that should really be queried at every ledger close. If you want to split RPC traffic, I'd rather see you use an actual proxy software for this and develop plugins there instead of modifying `rippled` into yet another mode or use case. Most probably https://github.com/ripple/rippled-historical-database is already 80% there of what you want this project to be by the way, it just seems that lately not that much has been going on in the JavaScript space at Ripple, so maybe this is the C++ team trying to cover more pieces of the stack?

Thanks for opening up that discussion instead of just dropping a pull request by the way, I hope this helps a bit.

PS: I think you can already tell `rippled` to not use any node database, and that mode is something I would run a validator in by default... so the "lean transaction processing mode" should already be a reality.

**Comment by cjcobb23** [comment]
The motivation behind putting this into rippled is code reuse. Reporting mode can handle almost the entire API without much effort, since it can use the exact same code for the RPC handlers. Otherwise, we would have to rewrite all of those handlers. To be clear, a future iteration of this project would split the reporting mode code out of rippled into a separate repo, with shared code in a third repo. For instance, the RPC handlers and the SHAMap code would be in this shared repo. Having a first iteration of this be a separate mode is a good way to get the ball rolling and test out the design, without having to make any changes to rippled in transaction processing mode; when we create the shared repo, we will have to rip all of the shared code out of rippled, which is a big change with a lot of room for error.

If we were to use https://github.com/ripple/rippled-historical-database, we would have to reimplement all of the rpc handlers in javascript. Very tedious.

By the way, reporting mode is basically just standalone mode, with an extra thread that is performing ETL and writing to the database. It's rather simple. 

About the load imposed by attaching a reporting node to a transaction processing node: The idea is that the same entity would be running both the transaction processing node and the reporting node, as opposed to just attaching your reporting node to any transaction processing node. The transaction processing node would only accept RPC traffic from the reporting node, so the load imposed on the transaction processing node would be predictable. It's really just a way to hide your transaction processing node from the public. If RPC traffic spikes really high, your reporting node is just going to temporarily lag behind, yet your transaction processing node would stay in sync with the network. This would allow you to still submit transactions, whereas if your transaction processing node desynced, you would not be able to submit transactions. 

On a more abstract level, the health of the peer to peer network is adversely affected any time nodes desync. Splitting reporting into a separate process sort of protects the peer to peer network, and keeps it healthy.

I agree that very expensive RPC calls are going to impose a lot of load on any server, regardless of mode. However, running in reporting mode, and not participating in the peer protocol, frees up additional resources to handle RPC requests. So I would expect that a reporting node would tolerate a higher load before being overwhelmed. And again, the behavior of a reporting node when it is overwhelmed is different than when a transaction processing node is overwhelmed: the reporting node will just be a few ledgers behind, and there would be no history gaps, no false negatives, and users would still be able to submit transactions. I would argue that this behavior leads to a better user experience when the system is under load, as compared to what happens currently when rippled is under high load.

We can consider using a shared cache in addition to a key-value store, but I wouldn't want to put all of the data into a shared cache. Some of these reporting nodes are going to be full history servers, and I don't think its the best idea to stuff full history into any sort of cache.

I'll check out envoy; thanks for the link. And thanks for this feedback; we appreciate it.

**Comment by scottschurr** [comment]
@cjcobb23, it looks like Reporting Mode was added to develop in 1.7.0-b11.  Is it time to close this issue?

**Comment by cjcobb23** [comment]
> @cjcobb23, it looks like Reporting Mode was added to develop in 1.7.0-b11.  Is it time to close this issue?

Yeah this can be closed now
