### ISSUE TITLE
Unexpected high fee (Version: 1.5.0)

### ISSUE THREAD

**Issue by abcdefg-hijklmnop** [ripple/rippled#3445]
Issue Description:
The API "fee" command, sometimes return a weird answer.
In the response structure, under "drops", there is a field named "open_ledger_fee". Its value in most cases is 10 as expected, but sometimes we are getting high values like 5125, 510$
This is a temporary answer, and If I call within a second or two, I get again the expected 10. So, I can't understand the logic of getting this high fee of more than 5000.

Steps to Reproduce:
Called "fee" API in loop for 100 times in a row.

![ripple-high-fee-bug](https://user-images.githubusercontent.com/51439443/83969438-b87fb180-a8d8-11ea-840a-ac382fd649b8.png)

**Comment by ximinez** [comment]
This behavior is intentional. See also:
* https://xrpl.org/fee.html#fee
* https://xrpl.org/transaction-cost.html
* https://xrpl.org/transaction-queue.html
If you submit a transaction with a fee between the `minimum_fee` and `open_ledger_fee`, it will likely be queued for a future ledger - most likely, this will be the very next ledger, so it won't need to wait more than a few extra seconds.

I'm going to close this ticket. If you have further questions or issues, feel free to re-open this ticket, or open a new one.
