### ISSUE TITLE
Shallow copying of ZeroCopyOutputStream

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3520]
ZeroCopyOutputStream has buffers_type::const_iterator pos_, which points to a place in buffers_.

If you ever copy a ZeroCopyOutputStream, the copy is shallow; destroying the original, means that pos_ in the copy now points to freed memory. I don’t know that we ever do this, but we should protect against this.

See https://github.com/ripple/rippled/blob/develop/src/ripple/overlay/impl/ZeroCopyStream.h

Exported from RIPD-1714

**Comment by gregtatcam** [comment]
The stream can not be copied by design. It inherits from google's protobuf ZeroCopyOutputStream, which blocks copy constructor:

`GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ZeroCopyOutputStream);`. 

This macro is defined as:

`#define GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(TypeName)    \
  TypeName(const TypeName&);                           \
  void operator=(const TypeName&)`
