### ISSUE TITLE
How to enable Ripple Data API v2 on own peer? (Version: 1.5.0)

### ISSUE THREAD

**Issue by SteelBRS** [ripple/rippled#3567]
I've been reading the documentation, but after some experimentation I've been unable to get this working.
I gives bad request when I try against a port configured with `http` ... but http means JSON-RPC ... how do I enable REST?

`http://<serverIP>:<port>/v2/accounts/<account>/orders`

**Comment by MarkusTeufelberger** [comment]
This is the wrong repository for this, the data API runs https://github.com/ripple/rippled-historical-database

**Comment by intelliot** [comment]
rippled does not provide a REST API. Depending on your use case, [rippled's JSON-RPC API](https://xrpl.org/get-started-with-the-rippled-api.html#json-rpc) may be a good choice.

**Comment by SteelBRS** [comment]
Erh ... historical?

I'm requesting the current offers/orders for an account ... doesn't seem like a historical query to me

**Comment by SteelBRS** [comment]
Also ... isn't it good practice to call stuff the same? An offer should be called 'offer' also in the ripple data API, and not an order, right?
Or am I missing something?

**Comment by MarkusTeufelberger** [comment]
> Erh ... this belongs in a repo with the word 'historical' in it?

Yes, because that is the repository that hosts the code that runs behind the "data API" - not this repository here.

**Comment by SteelBRS** [comment]
Thanks for the info Markus ... it's a fulltime job to answer stuff here, and Ripple doesn't even pay you ... I don't understand :smile:

**Comment by sublimator** [comment]
He keeps them honest! :)

>

**Comment by SteelBRS** [comment]
... and I finally stopped bitching and converted my REST call into a JSON-RPC 1.0 post ... in 15 minutes

**Comment by SteelBRS** [comment]
@sublimator you were the dude, that created the Java API back in the day, right?
I still don't understand why they dropped that ... doesn't Java still have the largest base of developers?

**Comment by sublimator** [comment]
Yeah, that's me!

I was never really a Java dev per se. It started as a weekend project to
learn ripple.
I was the only person who really used it at ripple so it bitrotted when I
left.

I updated a fork once for someone:
https://github.com/sublimator/ripple-lib-java

It's my thinking that they are focused on the XPring SDK now which has a
Java client ?
https://github.com/xpring-eng/xpring4j

It seems to use the javascript library for TXN serializing ?? :)

**Comment by cjcobb23** [comment]
We added gRPC support to rippled and are building xpring SDKs in a variety of languages using the gRPC requests that are supported by rippled

**Comment by intelliot** [comment]
This issue has been resolved. Here's a summary of the answer:

Q: How to enable Ripple Data API v2 on own peer?
A: [Ripple Data API](https://github.com/ripple/rippled-historical-database) is separate from rippled, which is the project that this issue was created in. Running your own instance of the Data API is complicated and usually unnecessary, as you can often retrieve the same data using rippled, e.g. with [rippled's JSON-RPC API](https://xrpl.org/get-started-with-the-rippled-api.html#json-rpc).

Q: How to retrieve an account's offers?
A: The [account_offers](https://xrpl.org/account_offers.html) method retrieves a list of offers made by a given account.

Note: `order` and `offer` are synonyms.

Hope this helps!
