### ISSUE TITLE
Successfully validated Offer not listed as as account offer

### ISSUE THREAD

**Issue by ottcsconsult** [ripple/rippled#3642]
Hi All,

I understand this may not be the ideal place to post this issue. However, I didn't find a better place and the xpring forum doesn't have a valid TLS certificate.

I submitted an offer. It was validated and it shows as successful. Yet it never showed up in the order book and it never showed up in method: "account_offers" (JSON RPC). Here is the TX hash:
4718EB82091A2343BA62D57C411D703E858537868B3B641971994FE9B5264006

https://xrpcharts.ripple.com/#/transactions/4718EB82091A2343BA62D57C411D703E858537868B3B641971994FE9B5264006

suggests it was successful. I placed this order on ask, a few ticks below the best ask. My offer size was tiny, while the next level was huge. I don't believe I need to prove that the problem is reproducible -- based on the TX information it should be clear why it was never included in the orderbook. I just don't see it from what is provided by rippled.

Why is it not included in the orderbook?

**Comment by ximinez** [comment]
That transaction was validated in ledger 59000273 and created an Offer node with LedgerIndex 3C50BE47A678593F09C69F89D1A62628FE39A7FA83A652D6DE91FE5C21DEDB73.

In *that same ledger*, there is a payment transaction that consumed the offer. You can see this if you expand AffectedNode with index 1 at https://xrpcharts.ripple.com/#/transactions/59BEC3684D799DEB7AF796E1C8A89919C0BDD98485221D1BD672CA292B8E7530

The `account_tx` command on a node with sufficient history will find this second transaction. You can also see the account history at https://livenet.xrpl.org/accounts/rrpJxQM16dqxHU75STd3Aonqp88RF1rWwf. Additionally, if you examine the balances, the XRP balance decreased, and the USD balance increased.

It's possible this is a coincidence, or there may be a bot watching offers and taking those it finds favorable. Either way, that's why you don't see the offer.

I'm going to close this issue, but if you have further questions please feel free to reopen it, or open a new issue.
