### ISSUE TITLE
How to get XRP account tag ? (Version: 1.6.0)

### ISSUE THREAD

**Issue by wc-codebase** [ripple/rippled#3664]
I'm working on XRP RPC for development XRP exchange platform.
I create XRP account by using ripple-lib api - api.generateAddress().
To enable new account, I need to make transaction and I need Tag.
I can't any reference for getting Tag from new XRP account.
Please help me.

**Comment by intelliot** [comment]
@wc-codebase For an account that you own, the destination tag is an arbitrary 32-bit unsigned integer. It is additional data that is embedded in a transaction.

If you generated the new account with `api.generateAddress()`, you can use any tag that you want. It just needs to be a 32-bit unsigned integer, so the minimum value is `0` and the maximum is `4294967295`. You can choose any number within that range.

> Source tags and destination tags are a feature of XRP Ledger payments that can indicate specific purposes for payments from and to multi-purpose addresses. Source and destination tags do not have direct on-ledger functionality; source and destination tags merely provide information about how off-ledger systems should process a payment.
- [Source and Destination Tags - xrpl.org](https://xrpl.org/source-and-destination-tags.html)

Typically, services like exchanges use tags to identify which client a particular deposit is intended for.

One rough analogy: When you own an account on the XRP Ledger, you could think of yourself as a "bank." Your account's classic address is the routing number, and the tag is the account number. Since you are the "bank," you have to determine, assign, and handle the account numbers (tags).

Does this help?

**Comment by ximinez** [comment]
Note, though, that tags are optional by default. If the account you're creating is personal, and doesn't need any of the types of divisions and record-keeping provided by destination tags, you don't need to use them.

**Comment by wc-codebase** [comment]
T

> 그러나 태그는 기본적으로 선택 사항입니다. 생성중인 계정이 개인 계정이고 대상 태그에서 제공하는 부서 및 기록 보관 유형이 필요하지 않은 경우에는 사용할 필요가 없습니다.
