### ISSUE TITLE
Weird "1" in parital offer TakerPays (Version: 1.6.0)

### ISSUE THREAD

**Issue by uioprty** [ripple/rippled#3665]
## Issue Description
Partial offer left weird accurate "1" in TakerPays, it'll leads to no deals in the same price
See the tx below

## Steps to Reproduce
First, create a offer to use 0.22 USD to exchange 0.1 XRP
Then, create a offer to use 0.2 XRP to exchange 0.44 USD

## Expected Result
Everything fine

## Actual Result
The remains offer left a weird 1 on the TakerPays of USD suffix. 

## Environment
Linux ubuntu 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
rippled version 1.6.0+DEBUG

## Supporting Files
{
	"result": {
		"Account": "rpZ2URQBB1wSyWYtMt2Z2FHmW2PLcHdqJj",
		"Fee": "10300",
		"Flags": 2148007936,
		"Sequence": 1085796,
		"SigningPubKey": "02FFCF921E5969B21B7F6A6AB41D4EFA893A932E238C601A8C5872E3042B689038",
		"TakerGets": "200000",
		"TakerPays": {
			"currency": "USD",
			"issuer": "rUBWU8f9EpKRxCKT3xoHD6Bj5rLLrwJrGn",
			"value": "0.44"
		},
		"TransactionType": "OfferCreate",
		"TxnSignature": "304402202D33E895D3D9454A183E611241DDF25BFF9E4A6ED98E5E68BA4FF0F5524C834A02207360DE64DAD399F8CED7A4AA2989678A251CF5D3DCD7E880E5C701548AC94ABD",
		"date": 658814310,
		"hash": "8F451BEE8C5BE64BB2D348C9C5042C715527C86A932C0917B379AB9C6F28B229",
		"inLedger": 1085841,
		"ledger_index": 1085841,
		"meta": {
			"AffectedNodes": [{
				"ModifiedNode": {
					"FinalFields": {
						"Account": "r4MaGDtPLckA8tCgPC3WvCiNmCZDAcxTyc",
						"Balance": "196062990",
						"Flags": 0,
						"OwnerCount": 1,
						"Sequence": 13
					},
					"LedgerEntryType": "AccountRoot",
					"LedgerIndex": "1748287CEEF1F2F05AF557DD18C36938F71FB23AF693D3AAF232DEFD0ADACE2E",
					"PreviousFields": {
						"Balance": "195962990",
						"OwnerCount": 2
					},
					"PreviousTxnID": "F666842203B03504A1E31FADF4A4B46FD2C580FCA3332AF4CC77E247E9469B15",
					"PreviousTxnLgrSeq": 1085838
				}
			}, {
				"DeletedNode": {
					"FinalFields": {
						"ExchangeRate": "5A1026111B8645D1",
						"Flags": 0,
						"RootIndex": "66AF99E9BFA45D6E3FF7F2EB18C7325796D73B62A40AC9D35A1026111B8645D1",
						"TakerGetsCurrency": "0000000000000000000000005553440000000000",
						"TakerGetsIssuer": "7AA5EBB4EA17D66D3D2F29AF2B82618B42DA88A8",
						"TakerPaysCurrency": "0000000000000000000000000000000000000000",
						"TakerPaysIssuer": "0000000000000000000000000000000000000000"
					},
					"LedgerEntryType": "DirectoryNode",
					"LedgerIndex": "66AF99E9BFA45D6E3FF7F2EB18C7325796D73B62A40AC9D35A1026111B8645D1"
				}
			}, {
				"ModifiedNode": {
					"FinalFields": {
						"Flags": 0,
						"Owner": "r4MaGDtPLckA8tCgPC3WvCiNmCZDAcxTyc",
						"RootIndex": "6A9FC26AB51438DE3EDEAFDD4CDC8DE917F9F5CD9CF8118B98029279D25959AF"
					},
					"LedgerEntryType": "DirectoryNode",
					"LedgerIndex": "6A9FC26AB51438DE3EDEAFDD4CDC8DE917F9F5CD9CF8118B98029279D25959AF"
				}
			}, {
				"ModifiedNode": {
					"FinalFields": {
						"Flags": 0,
						"Owner": "rpZ2URQBB1wSyWYtMt2Z2FHmW2PLcHdqJj",
						"RootIndex": "77673619F8F2B7A361EF7FCD0A1713867EE0F89813FB5880015C2792D5440065"
					},
					"LedgerEntryType": "DirectoryNode",
					"LedgerIndex": "77673619F8F2B7A361EF7FCD0A1713867EE0F89813FB5880015C2792D5440065"
				}
			}, {
				"DeletedNode": {
					"FinalFields": {
						"Account": "r4MaGDtPLckA8tCgPC3WvCiNmCZDAcxTyc",
						"BookDirectory": "66AF99E9BFA45D6E3FF7F2EB18C7325796D73B62A40AC9D35A1026111B8645D1",
						"BookNode": "0000000000000000",
						"Flags": 0,
						"OwnerNode": "0000000000000000",
						"PreviousTxnID": "F666842203B03504A1E31FADF4A4B46FD2C580FCA3332AF4CC77E247E9469B15",
						"PreviousTxnLgrSeq": 1085838,
						"Sequence": 12,
						"TakerGets": {
							"currency": "USD",
							"issuer": "rUBWU8f9EpKRxCKT3xoHD6Bj5rLLrwJrGn",
							"value": "0"
						},
						"TakerPays": "0"
					},
					"LedgerEntryType": "Offer",
					"LedgerIndex": "7980DB7848F1B4CCB7E7B3CA619D5344806AC6B2ACD23127BF5B19607311FDD4",
					"PreviousFields": {
						"TakerGets": {
							"currency": "USD",
							"issuer": "rUBWU8f9EpKRxCKT3xoHD6Bj5rLLrwJrGn",
							"value": "0.22"
						},
						"TakerPays": "100000"
					}
				}
			}, {
				"CreatedNode": {
					"LedgerEntryType": "DirectoryNode",
					"LedgerIndex": "9C0C407003BE96DFC1FB704BE9B99CC95FEDDD790A19D4334F07D0E36A818000",
					"NewFields": {
						"ExchangeRate": "4F07D0E36A818000",
						"RootIndex": "9C0C407003BE96DFC1FB704BE9B99CC95FEDDD790A19D4334F07D0E36A818000",
						"TakerPaysCurrency": "0000000000000000000000005553440000000000",
						"TakerPaysIssuer": "7AA5EBB4EA17D66D3D2F29AF2B82618B42DA88A8"
					}
				}
			}, {
				"ModifiedNode": {
					"FinalFields": {
						"Balance": {
							"currency": "USD",
							"issuer": "rrrrrrrrrrrrrrrrrrrrBZbvji",
							"value": "0.44"
						},
						"Flags": 65536,
						"HighLimit": {
							"currency": "USD",
							"issuer": "rUBWU8f9EpKRxCKT3xoHD6Bj5rLLrwJrGn",
							"value": "0"
						},
						"HighNode": "0000000000000002",
						"LowLimit": {
							"currency": "USD",
							"issuer": "rpZ2URQBB1wSyWYtMt2Z2FHmW2PLcHdqJj",
							"value": "1000000000000000e4"
						},
						"LowNode": "0000000000000000"
					},
					"LedgerEntryType": "RippleState",
					"LedgerIndex": "AD6F9400B57F36310DA32A54BB21C1443D0F1DB747D289686D36C5D13273ECA5",
					"PreviousFields": {
						"Balance": {
							"currency": "USD",
							"issuer": "rrrrrrrrrrrrrrrrrrrrBZbvji",
							"value": "0.22"
						}
					},
					"PreviousTxnID": "58D3C4A9894DFF63593AA67700438357402B996B0FD3A999575D8A9A8047FE52",
					"PreviousTxnLgrSeq": 1085835
				}
			}, {
				"ModifiedNode": {
					"FinalFields": {
						"Balance": {
							"currency": "USD",
							"issuer": "rrrrrrrrrrrrrrrrrrrrBZbvji",
							"value": "-1.71"
						},
						"Flags": 131072,
						"HighLimit": {
							"currency": "USD",
							"issuer": "r4MaGDtPLckA8tCgPC3WvCiNmCZDAcxTyc",
							"value": "1000000000000000e4"
						},
						"HighNode": "0000000000000000",
						"LowLimit": {
							"currency": "USD",
							"issuer": "rUBWU8f9EpKRxCKT3xoHD6Bj5rLLrwJrGn",
							"value": "0"
						},
						"LowNode": "0000000000000000"
					},
					"LedgerEntryType": "RippleState",
					"LedgerIndex": "B4085B9FB32E9295A8881F5D1FE6412193E7F555B0FAD6EE46E53A10262DE933",
					"PreviousFields": {
						"Balance": {
							"currency": "USD",
							"issuer": "rrrrrrrrrrrrrrrrrrrrBZbvji",
							"value": "-1.93"
						}
					},
					"PreviousTxnID": "58D3C4A9894DFF63593AA67700438357402B996B0FD3A999575D8A9A8047FE52",
					"PreviousTxnLgrSeq": 1085835
				}
			}, {
				"ModifiedNode": {
					"FinalFields": {
						"Account": "rpZ2URQBB1wSyWYtMt2Z2FHmW2PLcHdqJj",
						"Balance": "99779540",
						"Flags": 0,
						"OwnerCount": 2,
						"Sequence": 1085797
					},
					"LedgerEntryType": "AccountRoot",
					"LedgerIndex": "C7C5171AEE0BAF43B17CE9844115C136F2E563BE5757C58EC76EA4F8BEAB454A",
					"PreviousFields": {
						"Balance": "99889840",
						"OwnerCount": 1,
						"Sequence": 1085796
					},
					"PreviousTxnID": "58D3C4A9894DFF63593AA67700438357402B996B0FD3A999575D8A9A8047FE52",
					"PreviousTxnLgrSeq": 1085835
				}
			}, {
				"CreatedNode": {
					"LedgerEntryType": "Offer",
					"LedgerIndex": "E3BEAF7644410F657FB526CC78C870FA1F0CF460F0F2030A17A124C76A79055A",
					"NewFields": {
						"Account": "rpZ2URQBB1wSyWYtMt2Z2FHmW2PLcHdqJj",
						"BookDirectory": "9C0C407003BE96DFC1FB704BE9B99CC95FEDDD790A19D4334F07D0E36A818000",
						"Flags": 131072,
						"Sequence": 1085796,
						"TakerGets": "100000",
						"TakerPays": {
							"currency": "USD",
							"issuer": "rUBWU8f9EpKRxCKT3xoHD6Bj5rLLrwJrGn",
							"value": "0.2200000000000001"
						}
					}
				}
			}],
			"TransactionIndex": 0,
			"TransactionResult": "tesSUCCESS"
		},
		"status": "success",
		"validated": true
	}
}

**Comment by nbougalis** [comment]
I searched for transaction **`8F451BEE8C5BE64BB2D348C9C5042C715527C86A932C0917B379AB9C6F28B229`** on my personal servers and could not find it on either the testnet or the mainnet. So I am going to proceed with my analysis solely based on the metadata that you have provided here:

First, let's look at the transaction: **`rpZ..qJj`** tried to place an offer:
  `TakerGets`: **`0.200000` XRP**
  `TakerPays`: **`0.44` USD/rUB..rGn**

**`r4M..Tyc`** had an existing offer on the books:
  `TakesGets`: **`0.22` USD/rUB..rGn**
  `TakerPays`: **`0.100000` XRP**

During processing the **`rpZ..qJj`** offer crossed the **`r4M..Tyc`** offer and fully consumed it. The remaining part of the **`rpZ..qJj`** offer was placed on the books as:
 
  TakerPays: 0.2200000000000001
  TakerGets: 0.100000

You are concerned about the **0.2200000000000001** and more specifically, the **0.0000000000000001** which appears seemingly out of nowhere.

Before we talk about that, let's look at what the transaction execution actually did:

|   Account | XRP Balance Before | XRP Balance After | Difference | Explanation |
|:-:|-:|-:|-:|:-|
|`r4M..TyC` | `195.962990`         | `196.062990`        | `+0.100000`  | `0.100000` received from **..qJj** |
|`rpZ..qJj` |  `99.889840`         |  `99.779540`        | `-0.110300`  | `0.100000` sent to **..TyC** + `0.010300` fee|
| | | |  **`0.010300`**  | (the fee that was burned) |
                                                    

|   Account | USD Balance Before | USD Balance After | Explanation |
|:-:|-:|-:|:-|
|`r4M..Tyc` | `1.93`               | `1.71`              | `-0.22`      | `0.22` USD sent to **`rpZ..qJj`** |
|`rpZ..qJj` | `0.22`               | `0.44`              | `+0.22`      | `0.22` USD received from **`r4M..Tyc`** |
| |Difference   | **`0`**          | |

So the offer crossing was executed correctly, and there were no problems. Now, let's look at what happens after offer crossing to try and understand how that mysterious **0.0000000000000001** came to be:

Note that offers that are already on the books must be consumed at the rate at which they were placed, which may be different than the rate of an offer being processed. At the same time, the offer being placed must be placed at the same rate as the original amounts.

The combination of these two requirements means that we must first calculate the "quality" (i.e. the ratio of pays:gets) of the offer being placed and then to perform offer crossing, adjusting it down. Finally, after crossing completes, we want to readjust the pays and gets amounts to be at the original ratio. Alas, this isn't always possible because of how computers do arithmetic.

In theory, one would expect the resulting offer to be for _precisely_ **`0.22`** because we don't think about arithmetic the way computers do. To us it's obvious that **`0.22/0.1`** is precisely the same as **`0.44/0.2`**.

With computers, arithmetic is done at finite precision and sometimes the precision isn't enough to capture the result of the arithmetic operation. Furthermore, the code has take into account the quantized nature of XRP (the minimum quantity is 1 drop and it can't be subdivided). Because of these ~constraints~ factors, sometimes the resulting math used to "adjust" the rate at which an offer is placed to compensate for offer crossing can be off by some "dust" amounts. This seems to be the case here.

It would be nice to add some additional intelligence to detect such cases, but there would still be corner cases, so it's unclear (to me, at least) whether the benefits of doing that outweigh the costs.

I hope that this helps!

**Comment by uioprty** [comment]
Hi @nbougalis , it really helps. Thank you!

**Comment by uioprty** [comment]
Hi @nbougalis , it really helps. Thank you!

**Comment by nbougalis** [comment]
@uioprty Great. Please feel free to close this issue if you feel it's been resolved to your satisfaction. I'll schedule to close this sometime next week if you don't, unless you have something further to add.
