### ISSUE TITLE
TEc_PATH_DRY

### ISSUE THREAD

**Issue by qilinlab** [ripple/rippled#3728]
Hi Recently receving tec_PATH_DRY for any XRPL transaction thugh both parties trust the same issuer.
Also, not clear what no_ripple_peer means

Issuer:
https://xrpscan.com/account/r4KDrbRzU2BEAkXP2gn1yQymJ37GqhJM1G
Receiver:

https://xrpscan.com/account/rJoqJeg3smq4CxQzhLRtraH1BDBFZKUqVU

**Comment by mDuo13** [comment]
[`no_ripple_peer: true`](https://xrpl.org/rippling.html#looking-up-no-ripple-status) means that the counterparty (of whoever you looked up) has the No Ripple setting enabled on the trust line. In this case, your issuer has not enabled Default Ripple, so all trust lines opened to them have rippling disabled (the "No Ripple" setting enabled) by default, and this blocks funds from flowing through the issuer, as all issued currency payments must.

The idea behind No Ripple is to prevent third parties from moving funds through your account in a way that shifts your balances of currencies that have the same currency code but different issuers and therefore may have different practical valuations. Trading / general purpose accounts should have No Ripple enabled on their side of all their trust lines, which is what happens by default; however, issuers need to _disable_ No Ripple on all their trust lines to allow their customers to send the issued currency to each other.

So the issuer needs to [enable the Default Ripple setting](https://xrpl.org/become-an-xrp-ledger-gateway.html#default-ripple) so that all new trust lines have rippling enabled, and furthermore needs to go through its existing trust lines and manually enable rippling on all of them. The [`noripple_check` method](https://xrpl.org/noripple_check.html) can provide a list of suggested actions to take on an account.
