### ISSUE TITLE
 Ripple node does not give all transactions to the address (Version: 1.6.0)

### ISSUE THREAD

**Issue by HenryHelpteam** [ripple/rippled#3772]
I am a newbie. I've tried to run rippled on my Ubuntu 18.04 server. I've installed the ripple node according to the instructions https://xrpl.org/install-rippled.html. For some reasons, the ripple node does not give all transactions to the address. For example, there are only 7 transactions on one of the addresses, in fact, there are more than a hundred of them. What could be the reason for it? Where can I look for the cause? In logs?

**Comment by cjcobb23** [comment]
This is probably because your rippled server is not a full history server. rippled servers do not need to store the entire history of the XRP Ledger to function correctly. The server can function correctly with a very small subset of history. If you execute `server_info`, what is the value of `complete_ledgers`? This value is the range of history currently stored by your server. Full history is around 10TB, so it's not always desirable to store full history. In fact, the server continuously deletes older ledgers in order to save space. This process is called online delete. You can adjust the amount of history your server stores via the config file. More information about online delete can be found here: https://xrpl.org/configure-online-deletion.html . 

Here are instructions about how to configure full history, if you have the space and that's what you want: https://xrpl.org/configure-full-history.html

**Comment by HenryHelpteam** [comment]
Many thanks for the help. Your advices were very useful.
