### ISSUE TITLE
Offer not created on ledger when only partially filled (Version: 1.7)

### ISSUE THREAD

**Issue by Aquatrader** [ripple/rippled#3835]
## Issue Description
An offer was placed and partially filled. The remaining offer node was not created, and does not exist on the ledger.

## Steps to Reproduce
See transaction A5BCE9DECD8C0302E5BA7DE6C93E77E5710C89363E1848F8BF368A3D1D1FF089
## Expected Result
When an offer is partially filled, the remains are created as an offer node.
## Actual Result
Only the partial filled offer is processed, the remains are not.
## Environment
s1.ripple.com

**Comment by nbougalis** [comment]
Thanks for reporting this. We will look into this, but it _may_ be related with #3826. @seelabs can you please take a look? If this is a bug, please tag it as such.

**Comment by Aquatrader** [comment]
I have scanned the #3826. This order is not leaving a very small amount. I also do not see anything created on the wrong side of the orderbook. The order created was 3220 XRP. Only 36.605 XRP was filled. No order node was created for the remaining 3000+ XRP.
->I have to check if the order did cross an existing order. I have noticed my bot's performance is poor the last days. Did anaything change?

**Comment by seelabs** [comment]
@Aquatrader Thanks for reporting this. The reason the offer isn't being placed is because the account's XRP balance would below its required reserve if it were placed.

There are two rules to keep in mind:
1) The ledger requires an account to keep a minimum reserve of XRP. Right now, the reserve is a base of 20XRP plus an additional 5XRP for every object the account owns.
2) Offer crossing does not include new funds from the offer crossing when deciding if the account would dip below the reserve.

When the offer is first placed, the account has ~104.98XRP. If the partially filled offer were placed, the new reserve would be 105XRP. Even though the account's balance would be larger than the reserve if the new funds from the partially crossed offer were counted, offer crossing only considers the original funds. It's a bit of an edge case, but that is why the partially crossed offer wasn't placed.

**Comment by Aquatrader** [comment]
Ok, makes sense now :) +1 for lowering the account reserves
