### ISSUE TITLE
Negative UNL amendment

### ISSUE THREAD

**Issue by bharathchari** [ripple/rippled#3898]
The amendment corresponding to the NegativeUNL feature is not available for voting at this time.

The XRPL Foundation believes that the NegativeUNL functionality is critical to the long-term health of the XRPL, not only in principle but also in practice.

The code to introduce the amendment for this feature should be released immediately and made available in the form of an hotfix.

We are prepared to make such a release ourselves for validators who wish to deploy it.

**Comment by WietseWind** [comment]
+1

**Comment by crypticrabbit** [comment]
+1 - I believe the NegativeUNL is an overall great idea, and I think it would be appropriate to roll it in for voting with the next hotfix.

Based on my experiences running infrastructure and watching validation streams, the benefits to liveliness make this code worthy of being promoted to an actual amendment. It is asking a lot for validator operators to be available to respond instantaneously 24/7/365, and I know an amendment like this would have saved me some stress over the last few years!

Increasing the number of validators on the UNLs has alleviated some of the stress, however, I think the NegativeUNL is still a more robust idea, as it adds 20% more leeway (up to 40% of the original number of validators can be offline, rather than the current 20%).

I believe that the feature has been in testing since about v1.6.0, though I would also appreciate additional information about this.

**Comment by whywefight** [comment]
+1, if this has been tested and no issues are found.

**Comment by jonaagenilsen** [comment]
All for it :)

**Comment by firefly3582** [comment]
+1, good luck.
