### ISSUE TITLE
Decreased Stability since upgrade to 1.7.3

### ISSUE THREAD

**Issue by george-of-croton** [ripple/rippled#3988]
## Issue Description
Since upgrading to 1.7.3 I have noticed a considerable decrease in the stability of rippled. I have previously been running rippled 1.6 but was forced to upgrade after the recent ammendment. I am no noticing the increased  occurrence of the following errors: 

2021-Nov-17 06:56:42.917323016 UTC LoadManager:FTL Deadlock detected. Deadlocked time: 220s
2021-Nov-17 06:54:22.917328116 UTC LoadManager:WRN Server stalled for x seconds.
2021-Nov-17 10:16:18.844406645 UTC Validations:WRN Unable to determine hash of ancestor seq=1 from ledger hash=FCAE35E058FEA451935DDBB2718343C6BEFD02BBE6A60EDA118651D20A2EC791 seq=67756457
2021-Nov-17 07:32:38.539613409 UTC LedgerMaster:WRN SQL DB ledger sequence 67692559 mismatches node store

## Steps to Reproduce
i'm running rippled on a m5ad2xlarge instance.
 8 vcpu 
 32 gb ram
 300gb NVMe SSD. 
 so perhaps i am slightly light on RAM but i run [node_size] medium

if i run sudo service rippled restart there is about a 50/50 chance that i will hit the deadlock detected error. the other errors appears after the server has been synced for a period of time.

I should probably also note that this server processes ~800 - 1000 xrp transactions per day. So there is a not inconsiderable number of rpc calls being made.

## Expected Result
The server should start up and sync within 15 minutes.

## Actual Result
There is a significant chance that the server will encounter one of the errors mentioned.

## Environment
ubuntu xenial-16.04 aws AMI 
rippled 1.73

## Supporting Files
My config is more or less default apart from some tweaks to the rpc endpoints and
ledger_history = 10000
online_delete = 46400

I'm also using the default validators and servers lists

**Comment by ximinez** [comment]
When did you upgrade to 1.7.3?

**Comment by george-of-croton** [comment]
@ximinez november 12

**Comment by Crypto2** [comment]
Also having these issues here since upgrading to 1.7.3

**Comment by ximinez** [comment]
> november 12

The mainnet has seen an explosion in activity starting before November 12, which is putting strain on many nodes. Improvements are being worked on, several of which should be released soon in version 1.8.0. It's entirely possible that your 1.6 node was "on the edge" of stability, and but is unable to handle the extra load required to sync after restarting with 1.7.3.

Unfortunately, because 1.6.x is amendment blocked, it's impossible to try running that old version to see if the problem is specific to 1.7.3.

More likely, though, your hardware is simply insufficient to handle the extra load. Adding faster disks, more cores, and more memory may help. You can also try changing your `node_size` to `huge` since you have 32Gb of RAM. This will keep more information in memory for longer, which should decrease other disk activity.
