### ISSUE TITLE
cannot upgrade to 1.8.1 with https://mirrors.ripple.com/ripple-repo-el7.rpm

### ISSUE THREAD

**Issue by mangekyousharingan** [ripple/rippled#4003]
Hey,

tried to upgrade to 1.8.1 rippled version as usual by:
```
RIPPLE_VERSION 1.8.1
wget --no-check-certificate https://mirrors.ripple.com/ripple-repo-el7.rpm && \
rpm -Uvh ripple-repo-el7.rpm && \
yum install -y --enablerepo=ripple-stable rippled-$RIPPLE_VERSION
```
however it says _Error: Unable to find a match: rippled-1.8.1_, anything has change regarding it? 🤔

**Comment by nbougalis** [comment]
Hi! The **1.8.1** packages weren't uploaded to the **stable** package repo.

The rationale was that (a) there are several validators that are experiencing outages at this time and nodes with automatic updates restarting might aggravate the situation; and (b) the long Thanksgiving weekend in the United States is probably not the best of time to release a new package, because as [Murphy's Law](https://en.wikipedia.org/wiki/Murphy%27s_law) states, _"anything that can go wrong, will."_

If you'd like to update to **1.8.1** now, you should be able to use the **nightly** instead of the **stable** package.

**Comment by legleux** [comment]
1.8.1 has been pushed to the repos.
